/* Hoofbill — the cast. 25 horses, 25 toucans. */
const PROFILES = [
/* ── HORSES ───────────────────────────────────────────────── */
{id:'h00', kind:'horse', img:'img/horse_00.jpg', name:'Karakum', age:6,
 species:'Akhal-Teke', origin:'Turkmenistan',
 stat:['Height','15.2 hh'],
 bio:"Desert aristocrat currently doing a winter in the woods, which I'm told is character-building. My coat has a metallic sheen that photographs badly and ruins group shots for everyone else.",
 tags:['Metallic coat','Cold-weather brooding','Desert lineage'],
 prompt:['My simple pleasures','Standing perfectly still in bad weather so people think I am a statue.']},

{id:'h01', kind:'horse', img:'img/horse_01.jpg', name:'Freckle', age:9,
 species:'Appaloosa', origin:'Idaho, USA',
 stat:['Height','15.0 hh'],
 bio:"Born with one blue eye and a face full of freckles, so I've never had to develop a personality. Every single spot is in a different place than last year and nobody can explain it.",
 tags:['One blue eye','Freckled','Genetically confusing'],
 prompt:['Two truths and a lie','My spots move. My eye is blue. I am a normal horse.']},

{id:'h02', kind:'horse', img:'img/horse_02.jpg', name:'Zahra', age:8,
 species:'Arabian', origin:'Arabian Peninsula',
 stat:['Height','14.3 hh'],
 bio:"I have one fewer vertebra than most of you and I bring it up constantly. Dished face, high tail, five thousand years of paperwork.",
 tags:['Ancient bloodline','Dished profile','Unbearably refined'],
 prompt:["I'm looking for",'Someone who can keep up for 160 km and not make it weird.']},

{id:'h03', kind:'horse', img:'img/horse_03.jpg', name:'Sel', age:11,
 species:'Camargue', origin:'Camargue, France',
 stat:['Height','14.1 hh'],
 bio:"Born brown like everyone else, went grey, stayed grey, will be white forever. I live in a salt marsh and my feet are permanently damp — this is not a problem, it's a lifestyle.",
 tags:['Marsh-dwelling','Turns white','Wet hooves'],
 prompt:['A life goal of mine','Be photographed galloping through shallow water. Again. Professionally.']},

{id:'h04', kind:'horse', img:'img/horse_04.jpg', name:'Douglas', age:12,
 species:'Clydesdale', origin:'Lanarkshire, Scotland',
 stat:['Height','17.3 hh'],
 bio:"One tonne of Scottish draught horse in full harness. I wear blinkers because I am extremely easily distracted and we have all agreed this is for the best.",
 tags:['Feathered legs','Wears blinkers','Absolute unit'],
 prompt:['Dealbreaker','Anything moving in my peripheral vision. I cannot see it. It is ruining me.']},

{id:'h05', kind:'horse', img:'img/horse_05.jpg', name:'Bracken', age:14,
 species:'Exmoor Pony', origin:'Exmoor, England',
 stat:['Height','12.2 hh'],
 bio:"Semi-feral, fully unbothered. I have a double-layered winter coat, snow-proof eyelids, and a documented genetic link to Ice Age ponies, so yes, I will be standing outside.",
 tags:['Semi-feral','Ice Age genetics','Weatherproof'],
 prompt:['My most irrational fear','A rug. Someone once tried to put a rug on me.']},

{id:'h06', kind:'horse', img:'img/horse_06.jpg', name:'Bartolomé', age:7,
 species:'Falabella', origin:'Buenos Aires, Argentina',
 stat:['Height','7.1 hh'],
 bio:"Seventy-six centimetres of pure Argentine confidence. I am a horse. Not a pony. Not a dog. A horse. Please stop asking.",
 tags:['Miniature','Huge personality','Correctly a horse'],
 prompt:['Worst idea I ever had','Trying to establish dominance over a goose.']},

{id:'h07', kind:'horse', img:'img/horse_07.jpg', name:'Bjørn', age:10,
 species:'Norwegian Fjord', origin:'Western Norway',
 stat:['Height','14.0 hh'],
 bio:"My mane is trimmed upright to show the black stripe down the middle, which takes maintenance and I would love some acknowledgement of that. Vikings used me. I don't bring it up often.",
 tags:['Vertical haircut','Dun stripe','Viking résumé'],
 prompt:['I take pride in','A crest so structurally sound you could rest a coffee on it.']},

{id:'h08', kind:'horse', img:'img/horse_08.jpg', name:'Wybren', age:9,
 species:'Friesian', origin:'Friesland, Netherlands',
 stat:['Height','16.1 hh'],
 bio:"All black, all drama. I do carriage work, dressage, and — as you can see — the occasional historical procession with a man in a red cape. I have never had a subtle day in my life.",
 tags:['Theatrical','Jet black','Feathered'],
 prompt:['My love language','Arriving somewhere slowly, with music.']},

{id:'h09', kind:'horse', img:'img/horse_09.jpg', name:'Guinness', age:8,
 species:'Gypsy Cob', origin:'Britain & Ireland',
 stat:['Height','14.2 hh'],
 bio:"Piebald, feathered to the floor, forelock down to my nose. I genuinely cannot see and I have made my peace with it. Grooming me is a two-hour commitment — know that going in.",
 tags:['Enormous forelock','Piebald','High maintenance'],
 prompt:['Typical Sunday','Being brushed. Just — the entire day. Brushing.']},

{id:'h10', kind:'horse', img:'img/horse_10.jpg', name:'Gilda', age:11,
 species:'Haflinger', origin:'South Tyrol',
 stat:['Height','14.1 hh'],
 bio:"Chestnut body, platinum mane, permanently windswept. Every single Haflinger alive descends from one stallion born in 1874, so technically this is a very small family reunion.",
 tags:['Flaxen mane','Alpine','Aggressively photogenic'],
 prompt:['You should NOT go out with me if','You are intimidated by good hair.']},

{id:'h11', kind:'horse', img:'img/horse_11.jpg', name:'Þoka', age:13,
 species:'Icelandic Horse', origin:'Iceland',
 stat:['Height','13.2 hh'],
 bio:"I have five gaits instead of three. One of them is the tölt and it is so smooth you could carry a full glass. Once I leave Iceland I can never return, so I'm being very careful about holidays.",
 tags:['Five gaits','Cannot return home','Extremely fluffy'],
 prompt:['Fact about me that surprises people','There has been no new horse in Iceland since the year 982.']},

{id:'h12', kind:'horse', img:'img/horse_12.jpg', name:'Domino', age:7,
 species:'Knabstrupper', origin:'Denmark',
 stat:['Height','15.3 hh'],
 bio:"Danish, spotted, and descended from a single mare called Flaebe who showed up in 1812 covered in spots and started an entire breed. I contain multitudes. Roughly two hundred of them, countable.",
 tags:['Leopard-spotted','Circus heritage','Danish'],
 prompt:['A shower thought I recently had','If I stand in dappled shade, do I become invisible? (No.)']},

{id:'h13', kind:'horse', img:'img/horse_13.jpg', name:'Wiatr', age:10,
 species:'Konik', origin:'Poland',
 stat:['Height','13.1 hh'],
 bio:"Mouse-grey, dorsal-striped, and used across Europe for rewilding projects — which means my actual job is standing in a wetland looking primitive. It pays nothing and I love it.",
 tags:['Dorsal stripe','Rewilding professional','Primitive type'],
 prompt:['The key to my heart is','Not fencing me in. Genuinely. It is in my contract.']},

{id:'h14', kind:'horse', img:'img/horse_14.jpg', name:'Maestoso', age:15,
 species:'Lipizzaner', origin:'Lipica, Slovenia',
 stat:['Height','15.1 hh'],
 bio:"Born black, turned white at seven, as is tradition. I can do a capriole, which is a mid-air kick performed for no practical reason whatsoever, and I will be doing it at your party.",
 tags:['Airs above the ground','Born dark','Baroque'],
 prompt:['I geek out on','Levade form. Yours is fine. Mine is correct.']},

{id:'h15', kind:'horse', img:'img/horse_15.jpg', name:'Fado', age:9,
 species:'Lusitano', origin:'Alentejo, Portugal',
 stat:['Height','15.2 hh'],
 bio:"Dapple grey, bred for bullfighting, employed in dressage, spiritually a poet. I am extremely brave and extremely dramatic and those two things are the same thing.",
 tags:['Dappled','Iberian','Brave & moody'],
 prompt:['Best travel story','Portugal. All of it. I have not left.']},

{id:'h16', kind:'horse', img:'img/horse_16.jpg', name:'Café', age:8,
 species:'Mangalarga Marchador', origin:'Minas Gerais, Brazil',
 stat:['Height','15.0 hh'],
 bio:"Brazilian, chestnut, and gaited — my marcha is a four-beat glide with constant ground contact, meaning I never actually bounce you. Ask anyone. Nobody has ever bounced.",
 tags:['Gaited','Smooth ride','Brazilian'],
 prompt:['Something I will never do again','Trot. Why would I. I have a marcha.']},

{id:'h17', kind:'horse', img:'img/horse_17.jpg', name:'Rathore', age:11,
 species:'Marwari', origin:'Rajasthan, India',
 stat:['Height','15.1 hh'],
 bio:"My ears curve inward until the tips touch — this is the defining Marwari trait and also means I can hear you being sarcastic from a considerable distance. War horse by breeding, showman by choice.",
 tags:['Curved ear tips','Cavalry lineage','Ceremonial'],
 prompt:['A fact I am obligated to share','I can rotate my ears 180 degrees. Independently. Right now.']},

{id:'h18', kind:'horse', img:'img/horse_18.jpg', name:'Baatar', age:12,
 species:'Mongolian Horse', origin:'Mongolia',
 stat:['Height','13.0 hh'],
 bio:"Yes, I'm the small one in the distance — the steppe does that to everyone. There are more of us than there are people in Mongolia and we mostly live outdoors deciding our own business.",
 tags:['Free-ranging','Steppe-hardened','Outnumbers humans'],
 prompt:['My ideal first date','Forty kilometres. No conversation. Perfect.']},

{id:'h19', kind:'horse', img:'img/horse_19.jpg', name:'Juniper', age:6,
 species:'Mustang', origin:'Nevada, USA',
 stat:['Height','14.3 hh'],
 bio:"Free-roaming, descended from Spanish horses that got loose four hundred years ago and simply never went back. I come as a band. We travel together. Hope that's fine.",
 tags:['Free-roaming','Spanish descent','Band-oriented'],
 prompt:["I won't shut up about",'Water sources. I know all of them. Ask me. Please ask me.']},

{id:'h20', kind:'horse', img:'img/horse_20.jpg', name:'Cisco', age:7,
 species:'Paint Horse', origin:'Texas, USA',
 stat:['Height','15.1 hh'],
 bio:"Stock horse build, tobiano markings, one glass eye that unnerves strangers at shows. I turn on a coin and stop from a gallop in about three strides, which is showing off and I know it.",
 tags:['Tobiano','Glass eye','Ranch-capable'],
 prompt:['Change my mind','A sliding stop is a personality.']},

{id:'h21', kind:'horse', img:'img/horse_21.jpg', name:'Takhi', age:3,
 species:"Przewalski's Horse", origin:'Mongolian Steppe',
 stat:['Height','13.0 hh'],
 bio:"The last truly wild horse — never domesticated, extinct in the wild in 1969, back on the steppe now thanks to a lot of people being very stubborn on my behalf. I have 66 chromosomes. You have 64. Awkward.",
 tags:['Genuinely wild','Back from extinction','66 chromosomes'],
 prompt:['I want someone who','Understands that I am not a pony, I am a separate project.']},

{id:'h22', kind:'horse', img:'img/horse_22.jpg', name:'Nigel', age:16,
 species:'Shetland Pony', origin:'Shetland Isles',
 stat:['Height','9.3 hh'],
 bio:"Pound for pound the strongest horse alive, and I have chosen to use that power for crime. This is my good side. I am laughing at something I did earlier that you have not discovered yet.",
 tags:['Menace','Deceptively strong','No remorse'],
 prompt:['The way to win me over','You will not. You will simply learn to live alongside me.']},

{id:'h23', kind:'horse', img:'img/horse_23.jpg', name:'Bartholomew', age:10,
 species:'Shire', origin:'England',
 stat:['Height','18.0 hh'],
 bio:"The tallest horse ever recorded was one of mine — Sampson, 21.2 hands, 1846, still undefeated. I pull a tonne without breathing hard and my mane requires its own comb. Gentle. Enormous. Slow to anger.",
 tags:['Tallest breed','Gentle giant','Magnificent mane'],
 prompt:['Together we could','Move literally anything. Name it. It is moved.']},

{id:'h24', kind:'horse', img:'img/horse_24.jpg', name:'Clementine', age:13,
 species:'Suffolk Punch', origin:'Suffolk, England',
 stat:['Height','16.2 hh'],
 bio:"Every Suffolk alive traces to one stallion foaled in 1768, and there are fewer of us than there are giant pandas. Always chestnut. Always. There is no other option and we like it that way.",
 tags:['Always chestnut','Critically rare','Clean-legged'],
 prompt:['A cause I care about','Me. Statistically. Please.']},

/* ── TOUCANS ──────────────────────────────────────────────── */
{id:'t00', kind:'toucan', img:'img/toucan_00.jpg', name:'Nimbus', age:5,
 species:'Grey-breasted Mountain Toucan', origin:'Peruvian Andes',
 stat:['Bill','8 cm'],
 bio:"I live in cloud forest at 3,000 metres, where it is permanently damp and everything is covered in moss. I am grey, blue, chestnut and red all at once and I still count as subtle up here.",
 tags:['Cloud forest','High altitude','Moss enthusiast'],
 prompt:['My happy place','Inside a cloud. Technically always. Practically annoying.']},

{id:'t01', kind:'toucan', img:'img/toucan_01.jpg', name:'Plácido', age:6,
 species:'Plate-billed Mountain Toucan', origin:'Andes, Ecuador',
 stat:['Bill','9 cm'],
 bio:"There is a raised yellow plate on the side of my bill — an actual plate, like crockery — and no one has satisfactorily explained why. I have turquoise skin around my eye. I am, frankly, a lot.",
 tags:['Bill plate','Turquoise eye-ring','Unexplained anatomy'],
 prompt:['A question I ask constantly','But what is the plate FOR.']},

{id:'t02', kind:'toucan', img:'img/toucan_02.jpg', name:'Nubia', age:4,
 species:'Black-billed Mountain Toucan', origin:'Colombia',
 stat:['Bill','8 cm'],
 bio:"Colombian, Andean, and one of the few toucans who kept it tasteful with the bill. Blue-grey chest, chestnut back, small red flourish at the rear that I consider my signature.",
 tags:['Understated','Andean','Red accent'],
 prompt:['Unpopular opinion','Not every bill needs to be orange. There. Said it.']},

{id:'t03', kind:'toucan', img:'img/toucan_03.jpg', name:'Esmeralda', age:3,
 species:'Emerald Toucanet', origin:'Mexico',
 stat:['Bill','7 cm'],
 bio:"Small, green, and completely invisible in a leaf — which is the entire strategy. I nest in old woodpecker holes because building things is somebody else's job and always has been.",
 tags:['Leaf-green','Nests in borrowed holes','Tiny'],
 prompt:["I'm weirdly good at",'Being three feet from you, unseen, for an hour.']},

{id:'t04', kind:'toucan', img:'img/toucan_04.jpg', name:'Vinyl', age:5,
 species:'Groove-billed Toucanet', origin:'Venezuela',
 stat:['Bill','7 cm'],
 bio:"My bill has grooves running along it. Actual grooves. I have been called analogue more than once and I have decided to embrace it. Venezuelan cloud forest, permanently slightly damp.",
 tags:['Grooved bill','Cloud forest','Analogue'],
 prompt:['Two truths and a lie','I have grooves. I am green. I can be played at 33 rpm.']},

{id:'t05', kind:'toucan', img:'img/toucan_05.jpg', name:'Bernardo', age:7,
 species:'Black-necked Aracari', origin:'Brazil',
 stat:['Bill','10 cm'],
 bio:"Currently inspecting a tree cavity, as I do most afternoons. Up to six of us sleep in one hole, tails folded over our backs like a drawer of cutlery. It is undignified and extremely warm.",
 tags:['Communal rooster','Cavity nester','Tail folds flat'],
 prompt:['My most controversial take','Six is not too many for one hole. Seven is too many.']},

{id:'t06', kind:'toucan', img:'img/toucan_06.jpg', name:'Mostarda', age:4,
 species:'Saffron Toucanet', origin:'Misiones, Argentina',
 stat:['Bill','9 cm'],
 bio:"I am entirely yellow. Not accented with yellow — yellow. Red eye ring, red at the bill base, and the rest is pure saffron. Atlantic forest, threatened, unforgettable.",
 tags:['Entirely yellow','Red eye-ring','Rare'],
 prompt:["Don't hate me if I",'Clash with absolutely everything you own.']},

{id:'t07', kind:'toucan', img:'img/toucan_07.jpg', name:'Rizzo', age:6,
 species:'Curl-crested Aracari', origin:'Peru',
 stat:['Bill','11 cm'],
 bio:"The feathers on my head are not feathers — they're glossy black curls of hardened, enamel-like vinyl. I grew a perm. Nature gave me a perm and refuses to explain itself.",
 tags:['Vinyl curls','Amazonian','Natural perm'],
 prompt:['My greatest strength','Hair that cannot be ruined by weather because it is not hair.']},

{id:'t08', kind:'toucan', img:'img/toucan_08.jpg', name:'Castaña', age:5,
 species:'Chestnut-eared Aracari', origin:'Bolivia',
 stat:['Bill','11 cm'],
 bio:"Chestnut cheeks, yellow breast, a red band across the belly like a badly-placed belt. I travel in noisy gangs of a dozen and we arrive everywhere at once and leave immediately.",
 tags:['Travels in gangs','Red belly band','Loud arrival'],
 prompt:['A perfect evening','Twelve of us. One fig tree. Total chaos. Home by dusk.']},

{id:'t09', kind:'toucan', img:'img/toucan_09.jpg', name:'Inky', age:4,
 species:'Lettered Aracari', origin:'Amazonia',
 stat:['Bill','9 cm'],
 bio:"The black markings along my bill look like handwriting — hence the name — and people have spent real time trying to read them. There is nothing written there. I checked.",
 tags:['Calligraphic bill','Smallest aracari','Illegible'],
 prompt:['Ask me about','What my bill says. The answer is nothing. Ask anyway.']},

{id:'t10', kind:'toucan', img:'img/toucan_10.jpg', name:'Bandit', age:6,
 species:'Many-banded Aracari', origin:'Ecuador',
 stat:['Bill','11 cm'],
 bio:"Two red bands across a yellow belly, black hood, blue skin around the eye. I raid other birds' nests, which is a personality flaw I have chosen not to work on.",
 tags:['Double-banded','Nest raider','Unrepentant'],
 prompt:['I should probably apologise for','You know what I did.']},

{id:'t11', kind:'toucan', img:'img/toucan_11.jpg', name:'Colette', age:5,
 species:'Collared Aracari', origin:'Panama',
 stat:['Bill','10 cm'],
 bio:"Perched on a mossy branch, minding my own business, wearing a chestnut collar I did not choose but have grown into. I can turn my head 180 degrees and sleep with my bill tucked into my back.",
 tags:['Chestnut collar','Sleeps folded','Mossy branches'],
 prompt:['My sleep routine','Head backwards, bill under wing, tail flipped over. Fifteen seconds. Gone.']},

{id:'t12', kind:'toucan', img:'img/toucan_12.jpg', name:'Limón', age:3,
 species:'Green Aracari', origin:'Suriname',
 stat:['Bill','9 cm'],
 bio:"Smallest of all the toucans — about 130 grams, which is roughly a pear. Black hood if I'm male, chestnut if I'm female, and a bill striped like a strange citrus fruit.",
 tags:['Smallest toucan','Weighs a pear','Citrus bill'],
 prompt:['Small but','I will still take the best perch. Every time. Watch.']},

{id:'t13', kind:'toucan', img:'img/toucan_13.jpg', name:'Ramphael', age:8,
 species:'Toco Toucan', origin:'Pantanal, Brazil',
 stat:['Bill','20 cm'],
 bio:"The biggest bill in the business — a fifth of my entire length — and it weighs almost nothing because it's a honeycomb of keratin and air. I also use it as a radiator. Yes, really.",
 tags:['Largest toucan','Bill is a radiator','Mostly air'],
 prompt:['The most useless skill I have','My bill can dump body heat on demand. Impresses nobody at parties.']},

{id:'t14', kind:'toucan', img:'img/toucan_14.jpg', name:'Yolanda', age:6,
 species:'Yellow-throated Toucan', origin:'Costa Rica',
 stat:['Bill','15 cm'],
 bio:"Big, loud, and responsible for that yelping call you hear across the whole valley at dawn. People describe it as a frog. I find that hurtful and broadly accurate.",
 tags:['Extremely loud','Dawn caller','Sounds like a frog'],
 prompt:['My worst habit','6 a.m. Every day. Sorry. Not stopping.']},

{id:'t15', kind:'toucan', img:'img/toucan_15.jpg', name:'Coco', age:5,
 species:'Chocó Toucan', origin:'Chocó, Ecuador',
 stat:['Bill','14 cm'],
 bio:"I live in one of the wettest forests on Earth — the Chocó gets thirteen metres of rain a year in places. My bill is yellow and my outlook is damp but hopeful.",
 tags:['Rainforest specialist','Very wet','Yellow bill'],
 prompt:['A thing I have made peace with','Being moist. Perpetually. It is fine.']},

{id:'t16', kind:'toucan', img:'img/toucan_16.jpg', name:'Rubi', age:7,
 species:'Red-breasted Toucan', origin:'Atlantic Forest, Brazil',
 stat:['Bill','12 cm'],
 bio:"Also called the green-billed toucan, which undersells the enormous red-orange bib. Found in a pile of palm berries here, which is where I am most days, making a scene.",
 tags:['Red bib','Berry obsessive','Atlantic Forest'],
 prompt:['My most-used emoji would be','🫐 but for açaí. There is no emoji. This is an injustice.']},

{id:'t17', kind:'toucan', img:'img/toucan_17.jpg', name:'Iris', age:4,
 species:'Keel-billed Toucan', origin:'Belize',
 stat:['Bill','15 cm'],
 bio:"Green, orange, red and blue — all on one bill, all at once, entirely uncoordinated. National bird of Belize. I hop rather than fly wherever possible because flying is effortful and I am not.",
 tags:['Rainbow bill','National bird','Prefers hopping'],
 prompt:["I'd fall for you if",'You let me toss a berry at your face. It is courtship. Trust me.']},

{id:'t18', kind:'toucan', img:'img/toucan_18.jpg', name:'Tico', age:5,
 species:'Keel-billed Toucan', origin:'Belize',
 stat:['Bill','14 cm'],
 bio:"Same log, different bird. We sleep four to a hollow with our bills tucked back and our tails folded flat, which looks appalling and works perfectly. Ask my roommate Iris.",
 tags:['Rainbow bill','Roommate situation','Log-based lifestyle'],
 prompt:['A shared interest would be','This log. It is a good log. I want to talk about the log.']},

{id:'t19', kind:'toucan', img:'img/toucan_19.jpg', name:'Bico', age:9,
 species:'Toco Toucan', origin:'Pantanal, Brazil',
 stat:['Bill','19 cm'],
 bio:"Found in the open — cerrado, palm groves, riverbanks — rather than deep forest, which makes me the most extroverted toucan you will meet. Currently in a fig tree. Always currently in a fig tree.",
 tags:['Open country','Fig devotee','Extrovert'],
 prompt:['You should message me if','You have located fruit. That is the whole criterion.']},

{id:'t20', kind:'toucan', img:'img/toucan_20.jpg', name:'Bianca', age:6,
 species:'White-throated Toucan', origin:'Guyana',
 stat:['Bill','17 cm'],
 bio:"Crisp white bib, black body, and a call that carries for over a kilometre through solid rainforest. I am a critical seed disperser, which means entire trees exist because of my digestion.",
 tags:['White bib','Carries 1 km','Plants forests'],
 prompt:['My contribution to society','Several hundred trees. Passively. You are welcome.']},

{id:'t21', kind:'toucan', img:'img/toucan_21.jpg', name:'Papaya', age:5,
 species:'Channel-billed Toucan', origin:'Amazonia',
 stat:['Bill','13 cm'],
 bio:"Yellow throat bleeding into a deep orange chest, blue feet, and grooves — channels — running the length of my bill. I am the smaller Ramphastos and I have opinions about being called compact.",
 tags:['Sunset-coloured','Blue feet','Channelled bill'],
 prompt:['A word I dislike','Compact.']},

{id:'t22', kind:'toucan', img:'img/toucan_22.jpg', name:'Zafiro', age:7,
 species:'Channel-billed Toucan', origin:'Amazonia',
 stat:['Bill','13 cm'],
 bio:"This is a close-up of my eye, because it is turquoise and set in bare blue skin and I would like you to look at it properly. Yes, the rest of me exists. It is not the point.",
 tags:['Turquoise eye','Bare blue skin','Knows their angles'],
 prompt:['My best feature','Discussed at length above. Keep looking.']},

{id:'t23', kind:'toucan', img:'img/toucan_23.jpg', name:'Pip', age:4,
 species:'Spot-billed Toucanet', origin:'Paraná, Brazil',
 stat:['Bill','8 cm'],
 bio:"Small, olive-green, with dark spots along a pale bill and a golden ear patch. Atlantic Forest resident. Quiet. Frequently mistaken for a leaf with ambition.",
 tags:['Spotted bill','Golden ear patch','Quiet type'],
 prompt:['How to approach me','Slowly. I will leave. It is not personal, it is instinct.']},

{id:'t24', kind:'toucan', img:'img/toucan_24.jpg', name:'Midas', age:6,
 species:'Golden-collared Toucanet', origin:'Peru',
 stat:['Bill','8 cm'],
 bio:"Black head, chestnut-olive body, and a thin golden collar around the neck like a very restrained necklace. Males are black-headed, females chestnut — so you can tell us apart, which helps.",
 tags:['Gold collar','Sexually dimorphic','Restrained'],
 prompt:['My aesthetic in three words','One. Good. Accessory.']},
];
