/* Hoofbill — the cast. 51 horses, 50 toucans, 50 cows and one unicorn. */
const PROFILES = [
/* ── HORSES ───────────────────────────────────────────────── */
{id:'h00', sex:'m', kind:'horse', img:'img/horse_00.jpg', name:'Karakum', age:6,
 species:'Akhal-Teke', origin:'Turkmenistan',
 stat:['Height','15.2 hh'],
 bio:"Desert aristocrat currently doing a winter in the woods, which I'm told is character-building. My coat has a metallic sheen that photographs badly and ruins group shots for everyone else.",
 tags:['Metallic coat','Cold-weather brooding','Desert lineage'],
 prompt:['My simple pleasures','Standing perfectly still in bad weather so people think I am a statue.']},

{id:'h01', sex:'m', kind:'horse', img:'img/horse_01.jpg', name:'Freckle', age:9,
 species:'Appaloosa', origin:'Idaho, USA',
 stat:['Height','15.0 hh'],
 bio:"Born with one blue eye and a face full of freckles, so I've never had to develop a personality. Every single spot is in a different place than last year and nobody can explain it.",
 tags:['One blue eye','Freckled','Genetically confusing'],
 prompt:['Two truths and a lie','My spots move. My eye is blue. I am a normal horse.']},

{id:'h02', sex:'f', kind:'horse', img:'img/horse_02.jpg', name:'Zahra', age:8,
 species:'Arabian', origin:'Arabian Peninsula',
 stat:['Height','14.3 hh'],
 bio:"I have one fewer vertebra than most of you and I bring it up constantly. Dished face, high tail, five thousand years of paperwork.",
 tags:['Ancient bloodline','Dished profile','Unbearably refined'],
 prompt:["I'm looking for",'Someone who can keep up for 160 km and not make it weird.']},

{id:'h03', sex:'m', kind:'horse', img:'img/horse_03.jpg', name:'Sel', age:11,
 species:'Camargue', origin:'Camargue, France',
 stat:['Height','14.1 hh'],
 bio:"Born brown like everyone else, went grey, stayed grey, will be white forever. I live in a salt marsh and my feet are permanently damp — this is not a problem, it's a lifestyle.",
 tags:['Marsh-dwelling','Turns white','Wet hooves'],
 prompt:['A life goal of mine','Be photographed galloping through shallow water. Again. Professionally.']},

{id:'h04', sex:'m', kind:'horse', img:'img/horse_04.jpg', name:'Douglas', age:12,
 species:'Clydesdale', origin:'Lanarkshire, Scotland',
 stat:['Height','17.3 hh'],
 bio:"One tonne of Scottish draught horse in full harness. I wear blinkers because I am extremely easily distracted and we have all agreed this is for the best.",
 tags:['Feathered legs','Wears blinkers','Absolute unit'],
 prompt:['Dealbreaker','Anything moving in my peripheral vision. I cannot see it. It is ruining me.']},

{id:'h05', sex:'m', kind:'horse', img:'img/horse_05.jpg', name:'Bracken', age:14,
 species:'Exmoor Pony', origin:'Exmoor, England',
 stat:['Height','12.2 hh'],
 bio:"Semi-feral, fully unbothered. I have a double-layered winter coat, snow-proof eyelids, and a documented genetic link to Ice Age ponies, so yes, I will be standing outside.",
 tags:['Semi-feral','Ice Age genetics','Weatherproof'],
 prompt:['My most irrational fear','A rug. Someone once tried to put a rug on me.']},

{id:'h06', sex:'m', kind:'horse', img:'img/horse_06.jpg', name:'Bartolomé', age:7,
 species:'Falabella', origin:'Buenos Aires, Argentina',
 stat:['Height','7.2 hh'],
 bio:"Seventy-six centimetres of pure Argentine confidence. I am a horse. Not a pony. Not a dog. A horse. Please stop asking.",
 tags:['Miniature','Huge personality','Correctly a horse'],
 prompt:['Worst idea I ever had','Trying to establish dominance over a goose.']},

{id:'h07', sex:'m', kind:'horse', img:'img/horse_07.jpg', name:'Bjørn', age:10,
 species:'Norwegian Fjord', origin:'Western Norway',
 stat:['Height','14.0 hh'],
 bio:"My mane is trimmed upright to show the black stripe down the middle, which takes maintenance and I would love some acknowledgement of that. Vikings used me. I don't bring it up often.",
 tags:['Vertical haircut','Dun stripe','Viking résumé'],
 prompt:['I take pride in','A crest so structurally sound you could rest a coffee on it.']},

{id:'h08', sex:'m', kind:'horse', img:'img/horse_08.jpg', name:'Wybren', age:9,
 species:'Friesian', origin:'Friesland, Netherlands',
 stat:['Height','16.1 hh'],
 bio:"All black, all drama. I do carriage work, dressage, and — as you can see — the occasional historical procession with a man in a red cape. I have never had a subtle day in my life.",
 tags:['Theatrical','Jet black','Feathered'],
 prompt:['My love language','Arriving somewhere slowly, with music.']},

{id:'h09', sex:'m', kind:'horse', img:'img/horse_09.jpg', name:'Guinness', age:8,
 species:'Gypsy Cob', origin:'Britain & Ireland',
 stat:['Height','14.2 hh'],
 bio:"Piebald, feathered to the floor, forelock down to my nose. I genuinely cannot see and I have made my peace with it. Grooming me is a two-hour commitment — know that going in.",
 tags:['Enormous forelock','Piebald','High maintenance'],
 prompt:['Typical Sunday','Being brushed. Just — the entire day. Brushing.']},

{id:'h10', sex:'f', kind:'horse', img:'img/horse_10.jpg', name:'Gilda', age:11,
 species:'Haflinger', origin:'South Tyrol',
 stat:['Height','14.1 hh'],
 bio:"Chestnut body, platinum mane, permanently windswept. Every single Haflinger alive descends from one stallion born in 1874, so technically this is a very small family reunion.",
 tags:['Flaxen mane','Alpine','Aggressively photogenic'],
 prompt:['You should NOT go out with me if','You are intimidated by good hair.']},

{id:'h11', sex:'f', kind:'horse', img:'img/horse_11.jpg', name:'Þoka', age:13,
 species:'Icelandic Horse', origin:'Iceland',
 stat:['Height','13.2 hh'],
 bio:"I have five gaits instead of three. One of them is the tölt and it is so smooth you could carry a full glass. Once I leave Iceland I can never return, so I'm being very careful about holidays.",
 tags:['Five gaits','Cannot return home','Extremely fluffy'],
 prompt:['Fact about me that surprises people','There has been no new horse in Iceland since the year 982.']},

{id:'h12', sex:'m', kind:'horse', img:'img/horse_12.jpg', name:'Domino', age:7,
 species:'Knabstrupper', origin:'Denmark',
 stat:['Height','15.3 hh'],
 bio:"Danish, spotted, and descended from a single mare called Flaebe who showed up in 1812 covered in spots and started an entire breed. I contain multitudes. Roughly two hundred of them, countable.",
 tags:['Leopard-spotted','Circus heritage','Danish'],
 prompt:['A shower thought I recently had','If I stand in dappled shade, do I become invisible? (No.)']},

{id:'h13', sex:'m', kind:'horse', img:'img/horse_13.jpg', name:'Wiatr', age:10,
 species:'Konik', origin:'Poland',
 stat:['Height','13.1 hh'],
 bio:"Mouse-grey, dorsal-striped, and used across Europe for rewilding projects — which means my actual job is standing in a wetland looking primitive. It pays nothing and I love it.",
 tags:['Dorsal stripe','Rewilding professional','Primitive type'],
 prompt:['The key to my heart is','Not fencing me in. Genuinely. It is in my contract.']},

{id:'h14', sex:'m', kind:'horse', img:'img/horse_14.jpg', name:'Maestoso', age:15,
 species:'Lipizzaner', origin:'Lipica, Slovenia',
 stat:['Height','15.1 hh'],
 bio:"Born black, turned white at seven, as is tradition. I can do a capriole, which is a mid-air kick performed for no practical reason whatsoever, and I will be doing it at your party.",
 tags:['Airs above the ground','Born dark','Baroque'],
 prompt:['I geek out on','Levade form. Yours is fine. Mine is correct.']},

{id:'h15', sex:'m', kind:'horse', img:'img/horse_15.jpg', name:'Fado', age:9,
 species:'Lusitano', origin:'Alentejo, Portugal',
 stat:['Height','15.2 hh'],
 bio:"Dapple grey, bred for bullfighting, employed in dressage, spiritually a poet. I am extremely brave and extremely dramatic and those two things are the same thing.",
 tags:['Dappled','Iberian','Brave & moody'],
 prompt:['Best travel story','Portugal. All of it. I have not left.']},

{id:'h16', sex:'m', kind:'horse', img:'img/horse_16.jpg', name:'Café', age:8,
 species:'Mangalarga Marchador', origin:'Minas Gerais, Brazil',
 stat:['Height','15.0 hh'],
 bio:"Brazilian, chestnut, and gaited — my marcha is a four-beat glide with constant ground contact, meaning I never actually bounce you. Ask anyone. Nobody has ever bounced.",
 tags:['Gaited','Smooth ride','Brazilian'],
 prompt:['Something I will never do again','Trot. Why would I. I have a marcha.']},

{id:'h17', sex:'m', kind:'horse', img:'img/horse_17.jpg', name:'Rathore', age:11,
 species:'Marwari', origin:'Rajasthan, India',
 stat:['Height','15.1 hh'],
 bio:"My ears curve inward until the tips touch — this is the defining Marwari trait and also means I can hear you being sarcastic from a considerable distance. War horse by breeding, showman by choice.",
 tags:['Curved ear tips','Cavalry lineage','Ceremonial'],
 prompt:['A fact I am obligated to share','I can rotate my ears 180 degrees. Independently. Right now.']},

{id:'h18', sex:'m', kind:'horse', img:'img/horse_18.jpg', name:'Baatar', age:12,
 species:'Mongolian Horse', origin:'Mongolia',
 stat:['Height','13.0 hh'],
 bio:"Yes, I'm the small one in the distance — the steppe does that to everyone. There are more of us than there are people in Mongolia and we mostly live outdoors deciding our own business.",
 tags:['Free-ranging','Steppe-hardened','Outnumbers humans'],
 prompt:['My ideal first date','Forty kilometres. No conversation. Perfect.']},

{id:'h19', sex:'f', kind:'horse', img:'img/horse_19.jpg', name:'Juniper', age:6,
 species:'Mustang', origin:'Nevada, USA',
 stat:['Height','14.3 hh'],
 bio:"Free-roaming, descended from Spanish horses that got loose four hundred years ago and simply never went back. I come as a band. We travel together. Hope that's fine.",
 tags:['Free-roaming','Spanish descent','Band-oriented'],
 prompt:["I won't shut up about",'Water sources. I know all of them. Ask me. Please ask me.']},

{id:'h20', sex:'m', kind:'horse', img:'img/horse_20.jpg', name:'Cisco', age:7,
 species:'Paint Horse', origin:'Texas, USA',
 stat:['Height','15.1 hh'],
 bio:"Stock horse build, tobiano markings, one glass eye that unnerves strangers at shows. I turn on a coin and stop from a gallop in about three strides, which is showing off and I know it.",
 tags:['Tobiano','Glass eye','Ranch-capable'],
 prompt:['Change my mind','A sliding stop is a personality.']},

{id:'h21', sex:'m', kind:'horse', img:'img/horse_21.jpg', name:'Takhi', age:3,
 species:"Przewalski's Horse", origin:'Mongolian Steppe',
 stat:['Height','13.0 hh'],
 bio:"The last truly wild horse — never domesticated, extinct in the wild in 1969, back on the steppe now thanks to a lot of people being very stubborn on my behalf. I have 66 chromosomes. You have 64. Awkward.",
 tags:['Genuinely wild','Back from extinction','66 chromosomes'],
 prompt:['I want someone who','Understands that I am not a pony, I am a separate project.']},

{id:'h22', sex:'m', kind:'horse', img:'img/horse_22.jpg', name:'Nigel', age:16,
 species:'Shetland Pony', origin:'Shetland Isles',
 stat:['Height','9.3 hh'],
 bio:"Pound for pound the strongest horse alive, and I have chosen to use that power for crime. This is my good side. I am laughing at something I did earlier that you have not discovered yet.",
 tags:['Menace','Deceptively strong','No remorse'],
 prompt:['The way to win me over','You will not. You will simply learn to live alongside me.']},

{id:'h23', sex:'m', kind:'horse', img:'img/horse_23.jpg', name:'Bartholomew', age:10,
 species:'Shire', origin:'England',
 stat:['Height','18.0 hh'],
 bio:"The tallest horse ever recorded was one of mine — Sampson, 21.2 hands, 1846, still undefeated. I pull a tonne without breathing hard and my mane requires its own comb. Gentle. Enormous. Slow to anger.",
 tags:['Tallest breed','Gentle giant','Magnificent mane'],
 prompt:['Together we could','Move literally anything. Name it. It is moved.']},

{id:'h24', sex:'f', kind:'horse', img:'img/horse_24.jpg', name:'Clementine', age:13,
 species:'Suffolk Punch', origin:'Suffolk, England',
 stat:['Height','16.2 hh'],
 bio:"Every Suffolk alive traces to one stallion foaled in 1768, and there are fewer of us than there are giant pandas. Always chestnut. Always. There is no other option and we like it that way.",
 tags:['Always chestnut','Critically rare','Clean-legged'],
 prompt:['A cause I care about','Me. Statistically. Please.']},

/* ── TOUCANS ──────────────────────────────────────────────── */
{id:'t00', sex:'m', kind:'toucan', img:'img/toucan_00.jpg', name:'Nimbus', age:5,
 species:'Grey-breasted Mountain Toucan', origin:'Peruvian Andes',
 stat:['Bill','8 cm'],
 bio:"I live in cloud forest at 3,000 metres, where it is permanently damp and everything is covered in moss. I am grey, blue, chestnut and red all at once and I still count as subtle up here.",
 tags:['Cloud forest','High altitude','Moss enthusiast'],
 prompt:['My happy place','Inside a cloud. Technically always. Practically annoying.']},

{id:'t01', sex:'m', kind:'toucan', img:'img/toucan_01.jpg', name:'Plácido', age:6,
 species:'Plate-billed Mountain Toucan', origin:'Andes, Ecuador',
 stat:['Bill','9 cm'],
 bio:"There is a raised yellow plate on the side of my bill — an actual plate, like crockery — and no one has satisfactorily explained why. I have turquoise skin around my eye. I am, frankly, a lot.",
 tags:['Bill plate','Turquoise eye-ring','Unexplained anatomy'],
 prompt:['A question I ask constantly','But what is the plate FOR.']},

{id:'t02', sex:'f', kind:'toucan', img:'img/toucan_02.jpg', name:'Nubia', age:4,
 species:'Black-billed Mountain Toucan', origin:'Colombia',
 stat:['Bill','8 cm'],
 bio:"Colombian, Andean, and one of the few toucans who kept it tasteful with the bill. Blue-grey chest, chestnut back, small red flourish at the rear that I consider my signature.",
 tags:['Understated','Andean','Red accent'],
 prompt:['Unpopular opinion','Not every bill needs to be orange. There. Said it.']},

{id:'t03', sex:'f', kind:'toucan', img:'img/toucan_03.jpg', name:'Esmeralda', age:3,
 species:'Emerald Toucanet', origin:'Mexico',
 stat:['Bill','7 cm'],
 bio:"Small, green, and completely invisible in a leaf — which is the entire strategy. I nest in old woodpecker holes because building things is somebody else's job and always has been.",
 tags:['Leaf-green','Nests in borrowed holes','Tiny'],
 prompt:["I'm weirdly good at",'Being three feet from you, unseen, for an hour.']},

{id:'t04', sex:'m', kind:'toucan', img:'img/toucan_04.jpg', name:'Vinyl', age:5,
 species:'Groove-billed Toucanet', origin:'Venezuela',
 stat:['Bill','7 cm'],
 bio:"My bill has grooves running along it. Actual grooves. I have been called analogue more than once and I have decided to embrace it. Venezuelan cloud forest, permanently slightly damp.",
 tags:['Grooved bill','Cloud forest','Analogue'],
 prompt:['Two truths and a lie','I have grooves. I am green. I can be played at 33 rpm.']},

{id:'t05', sex:'m', kind:'toucan', img:'img/toucan_05.jpg', name:'Bernardo', age:7,
 species:'Black-necked Aracari', origin:'Brazil',
 stat:['Bill','10 cm'],
 bio:"Currently inspecting a tree cavity, as I do most afternoons. Up to six of us sleep in one hole, tails folded over our backs like a drawer of cutlery. It is undignified and extremely warm.",
 tags:['Communal rooster','Cavity nester','Tail folds flat'],
 prompt:['My most controversial take','Six is not too many for one hole. Seven is too many.']},

{id:'t06', sex:'f', kind:'toucan', img:'img/toucan_06.jpg', name:'Mostarda', age:4,
 species:'Saffron Toucanet', origin:'Misiones, Argentina',
 stat:['Bill','9 cm'],
 bio:"I am entirely yellow. Not accented with yellow — yellow. Red eye ring, red at the bill base, and the rest is pure saffron. Atlantic forest, threatened, unforgettable.",
 tags:['Entirely yellow','Red eye-ring','Rare'],
 prompt:["Don't hate me if I",'Clash with absolutely everything you own.']},

{id:'t07', sex:'m', kind:'toucan', img:'img/toucan_07.jpg', name:'Rizzo', age:6,
 species:'Curl-crested Aracari', origin:'Peru',
 stat:['Bill','11 cm'],
 bio:"The feathers on my head are not feathers — they're glossy black curls of hardened, enamel-like vinyl. I grew a perm. Nature gave me a perm and refuses to explain itself.",
 tags:['Vinyl curls','Amazonian','Natural perm'],
 prompt:['My greatest strength','Hair that cannot be ruined by weather because it is not hair.']},

{id:'t08', sex:'f', kind:'toucan', img:'img/toucan_08.jpg', name:'Castaña', age:5,
 species:'Chestnut-eared Aracari', origin:'Bolivia',
 stat:['Bill','11 cm'],
 bio:"Chestnut cheeks, yellow breast, a red band across the belly like a badly-placed belt. I travel in noisy gangs of a dozen and we arrive everywhere at once and leave immediately.",
 tags:['Travels in gangs','Red belly band','Loud arrival'],
 prompt:['A perfect evening','Twelve of us. One fig tree. Total chaos. Home by dusk.']},

{id:'t09', sex:'m', kind:'toucan', img:'img/toucan_09.jpg', name:'Inky', age:4,
 species:'Lettered Aracari', origin:'Amazonia',
 stat:['Bill','9 cm'],
 bio:"The black markings along my bill look like handwriting — hence the name — and people have spent real time trying to read them. There is nothing written there. I checked.",
 tags:['Calligraphic bill','Smallest aracari','Illegible'],
 prompt:['Ask me about','What my bill says. The answer is nothing. Ask anyway.']},

{id:'t10', sex:'m', kind:'toucan', img:'img/toucan_10.jpg', name:'Bandit', age:6,
 species:'Many-banded Aracari', origin:'Ecuador',
 stat:['Bill','11 cm'],
 bio:"Two red bands across a yellow belly, black hood, blue skin around the eye. I raid other birds' nests, which is a personality flaw I have chosen not to work on.",
 tags:['Double-banded','Nest raider','Unrepentant'],
 prompt:['I should probably apologise for','You know what I did.']},

{id:'t11', sex:'f', kind:'toucan', img:'img/toucan_11.jpg', name:'Colette', age:5,
 species:'Collared Aracari', origin:'Panama',
 stat:['Bill','10 cm'],
 bio:"Perched on a mossy branch, minding my own business, wearing a chestnut collar I did not choose but have grown into. I can turn my head 180 degrees and sleep with my bill tucked into my back.",
 tags:['Chestnut collar','Sleeps folded','Mossy branches'],
 prompt:['My sleep routine','Head backwards, bill under wing, tail flipped over. Fifteen seconds. Gone.']},

{id:'t12', sex:'m', kind:'toucan', img:'img/toucan_12.jpg', name:'Limón', age:3,
 species:'Green Aracari', origin:'Suriname',
 stat:['Bill','9 cm'],
 bio:"Smallest of all the toucans — about 130 grams, which is roughly a pear. Black hood if I'm male, chestnut if I'm female, and a bill striped like a strange citrus fruit.",
 tags:['Smallest toucan','Weighs a pear','Citrus bill'],
 prompt:['Small but','I will still take the best perch. Every time. Watch.']},

{id:'t13', sex:'m', kind:'toucan', img:'img/toucan_13.jpg', name:'Ramphael', age:8,
 species:'Toco Toucan', origin:'Pantanal, Brazil',
 stat:['Bill','20 cm'],
 bio:"The biggest bill in the business — a fifth of my entire length — and it weighs almost nothing because it's a honeycomb of keratin and air. I also use it as a radiator. Yes, really.",
 tags:['Largest toucan','Bill is a radiator','Mostly air'],
 prompt:['The most useless skill I have','My bill can dump body heat on demand. Impresses nobody at parties.']},

{id:'t14', sex:'f', kind:'toucan', img:'img/toucan_14.jpg', name:'Yolanda', age:6,
 species:'Yellow-throated Toucan', origin:'Costa Rica',
 stat:['Bill','15 cm'],
 bio:"Big, loud, and responsible for that yelping call you hear across the whole valley at dawn. People describe it as a frog. I find that hurtful and broadly accurate.",
 tags:['Extremely loud','Dawn caller','Sounds like a frog'],
 prompt:['My worst habit','6 a.m. Every day. Sorry. Not stopping.']},

{id:'t15', sex:'f', kind:'toucan', img:'img/toucan_15.jpg', name:'Coco', age:5,
 species:'Chocó Toucan', origin:'Chocó, Ecuador',
 stat:['Bill','14 cm'],
 bio:"I live in one of the wettest forests on Earth — the Chocó gets thirteen metres of rain a year in places. My bill is yellow and my outlook is damp but hopeful.",
 tags:['Rainforest specialist','Very wet','Yellow bill'],
 prompt:['A thing I have made peace with','Being moist. Perpetually. It is fine.']},

{id:'t16', sex:'f', kind:'toucan', img:'img/toucan_16.jpg', name:'Rubi', age:7,
 species:'Red-breasted Toucan', origin:'Atlantic Forest, Brazil',
 stat:['Bill','12 cm'],
 bio:"Also called the green-billed toucan, which undersells the enormous red-orange bib. Found in a pile of palm berries here, which is where I am most days, making a scene.",
 tags:['Red bib','Berry obsessive','Atlantic Forest'],
 prompt:['My most-used emoji would be','🫐 but for açaí. There is no emoji. This is an injustice.']},

{id:'t17', sex:'f', kind:'toucan', img:'img/toucan_17.jpg', name:'Iris', age:4,
 species:'Keel-billed Toucan', origin:'Belize',
 stat:['Bill','15 cm'],
 bio:"Green, orange, red and blue — all on one bill, all at once, entirely uncoordinated. National bird of Belize. I hop rather than fly wherever possible because flying is effortful and I am not.",
 tags:['Rainbow bill','National bird','Prefers hopping'],
 prompt:["I'd fall for you if",'You let me toss a berry at your face. It is courtship. Trust me.']},

{id:'t18', sex:'m', kind:'toucan', img:'img/toucan_18.jpg', name:'Tico', age:5,
 species:'Keel-billed Toucan', origin:'Belize',
 stat:['Bill','14 cm'],
 bio:"Same log, different bird. We sleep four to a hollow with our bills tucked back and our tails folded flat, which looks appalling and works perfectly. Ask my roommate Iris.",
 tags:['Rainbow bill','Roommate situation','Log-based lifestyle'],
 prompt:['A shared interest would be','This log. It is a good log. I want to talk about the log.']},

{id:'t19', sex:'m', kind:'toucan', img:'img/toucan_19.jpg', name:'Bico', age:9,
 species:'Toco Toucan', origin:'Pantanal, Brazil',
 stat:['Bill','19 cm'],
 bio:"Found in the open — cerrado, palm groves, riverbanks — rather than deep forest, which makes me the most extroverted toucan you will meet. Currently in a fig tree. Always currently in a fig tree.",
 tags:['Open country','Fig devotee','Extrovert'],
 prompt:['You should message me if','You have located fruit. That is the whole criterion.']},

{id:'t20', sex:'f', kind:'toucan', img:'img/toucan_20.jpg', name:'Bianca', age:6,
 species:'White-throated Toucan', origin:'Guyana',
 stat:['Bill','17 cm'],
 bio:"Crisp white bib, black body, and a call that carries for over a kilometre through solid rainforest. I am a critical seed disperser, which means entire trees exist because of my digestion.",
 tags:['White bib','Carries 1 km','Plants forests'],
 prompt:['My contribution to society','Several hundred trees. Passively. You are welcome.']},

{id:'t21', sex:'f', kind:'toucan', img:'img/toucan_21.jpg', name:'Papaya', age:5,
 species:'Channel-billed Toucan', origin:'Amazonia',
 stat:['Bill','13 cm'],
 bio:"Yellow throat bleeding into a deep orange chest, blue feet, and grooves — channels — running the length of my bill. I am the smaller Ramphastos and I have opinions about being called compact.",
 tags:['Sunset-coloured','Blue feet','Channelled bill'],
 prompt:['A word I dislike','Compact.']},

{id:'t22', sex:'m', kind:'toucan', img:'img/toucan_22.jpg', name:'Zafiro', age:7,
 species:'Channel-billed Toucan', origin:'Amazonia',
 stat:['Bill','13 cm'],
 bio:"This is a close-up of my eye, because it is turquoise and set in bare blue skin and I would like you to look at it properly. Yes, the rest of me exists. It is not the point.",
 tags:['Turquoise eye','Bare blue skin','Knows their angles'],
 prompt:['My best feature','Discussed at length above. Keep looking.']},

{id:'t23', sex:'m', kind:'toucan', img:'img/toucan_23.jpg', name:'Pip', age:4,
 species:'Spot-billed Toucanet', origin:'Paraná, Brazil',
 stat:['Bill','8 cm'],
 bio:"Small, olive-green, with dark spots along a pale bill and a golden ear patch. Atlantic Forest resident. Quiet. Frequently mistaken for a leaf with ambition.",
 tags:['Spotted bill','Golden ear patch','Quiet type'],
 prompt:['How to approach me','Slowly. I will leave. It is not personal, it is instinct.']},

{id:'t24', sex:'m', kind:'toucan', img:'img/toucan_24.jpg', name:'Midas', age:6,
 species:'Golden-collared Toucanet', origin:'Peru',
 stat:['Bill','8 cm'],
 bio:"Black head, chestnut-olive body, and a thin golden collar around the neck like a very restrained necklace. Males are black-headed, females chestnut — so you can tell us apart, which helps.",
 tags:['Gold collar','Sexually dimorphic','Restrained'],
 prompt:['My aesthetic in three words','One. Good. Accessory.']},

/* ── MORE HORSES ──────────────────────────────────────────── */
{id:'h25', sex:'m', kind:'horse', img:'img/horse_25.jpg', name:'Altyn', age:7,
 species:'Akhal-Teke', origin:'Turkmenistan',
 stat:['Height','15.3 hh'],
 bio:"My coat contains a hair structure that refracts light, which is a scientific way of saying I glow. The breed is on the national emblem of Turkmenistan. I keep a copy of it.",
 tags:['Actually glows','On the money','Desert-bred'],
 prompt:['My most useless talent','Ruining everyone else’s photographs by being slightly luminous.']},

{id:'h26', sex:'f', kind:'horse', img:'img/horse_26.jpg', name:'Dolly', age:9,
 species:'Quarter Horse', origin:'Oklahoma, USA',
 stat:['Height','15.1 hh'],
 bio:"Fastest horse alive over a quarter mile — 55 mph, and then I am completely finished and need a lie-down. There are more of us registered than any other breed on Earth, so do temper your expectations.",
 tags:['55 mph','Sprinter','Extremely common'],
 prompt:['My worst quality','Stamina. Ask me again in four hundred metres.']},

{id:'h27', sex:'m', kind:'horse', img:'img/horse_27.jpg', name:'Marbles', age:12,
 species:'Appaloosa', origin:'Idaho, USA',
 stat:['Height','15.0 hh'],
 bio:"Mottled skin, striped hooves, and a white sclera around the eye that makes me look permanently appalled. I am not appalled. This is just my face and I would appreciate the benefit of the doubt.",
 tags:['Striped hooves','Visible sclera','Not actually appalled'],
 prompt:['A common misconception about me','That I have just heard something shocking.']},

{id:'h28', sex:'f', kind:'horse', img:'img/horse_28.jpg', name:'Nejma', age:8,
 species:'Arabian', origin:'Arabian Peninsula',
 stat:['Height','14.3 hh'],
 bio:"Currently in ceremonial tack with purple tassels, which was not my decision but which I am carrying extremely well. Bedouin tribes kept mares inside the family tent. I have never recovered from that standard of accommodation.",
 tags:['Ceremonial','Purple tassels','Used to luxury'],
 prompt:['Where I see myself in five years','Inside. Preferably your tent.']},

{id:'h29', sex:'m', kind:'horse', img:'img/horse_29.jpg', name:'Roland', age:11,
 species:'Ardennais', origin:'Ardennes, Belgium',
 stat:['Height','16.0 hh'],
 bio:"One of the oldest draught breeds in Europe — Caesar's legions are said to have used my ancestors, and Napoleon took us to Russia. These days I stand in a field. It is a better arrangement for everyone.",
 tags:['Ancient draught','Roman CV','Retired from war'],
 prompt:['A hill I will die on','Pulling things is honest work. Dressage is a hobby.']},

{id:'h30', sex:'f', kind:'horse', img:'img/horse_30.jpg', name:'Mistral', age:14,
 species:'Camargue', origin:'Camargue, France',
 stat:['Height','14.2 hh'],
 bio:"That dark one is mine. Camargue foals are born black or brown and go white over four or five years, so for a while I look like I have adopted a small shadow. Eventually he'll match.",
 tags:['Mother','Born dark','Marsh mare'],
 prompt:['Something I did not expect','How much of my personality would become “parent”.']},

{id:'h31', sex:'f', kind:'horse', img:'img/horse_31.jpg', name:'Pepita', age:5,
 species:'Falabella', origin:'Buenos Aires, Argentina',
 stat:['Height','7.0 hh'],
 bio:"Bred down over generations on one Argentine ranch until we arrived here, at roughly the size of a large dog. I have the same number of ribs as a full-sized horse, just closer together. It is a design triumph.",
 tags:['Ranch-bred','Full rib count','Dog-adjacent'],
 prompt:['My party trick','Walking under things. All of the things.']},

{id:'h32', sex:'m', kind:'horse', img:'img/horse_32.jpg', name:'Sooty', age:10,
 species:'Fell Pony', origin:'Cumbria, England',
 stat:['Height','13.2 hh'],
 bio:"Black, feathered, and built by the weather on the wrong side of the Pennines. I used to carry lead ore across the fells for a living. Now I trot about looking dramatic in wet grass, which pays worse but suits me.",
 tags:['Pack-pony heritage','Feathered','Fell-bred'],
 prompt:['My ideal Sunday','Rain. Horizontal rain. Ideally sideways.']},

{id:'h33', sex:'f', kind:'horse', img:'img/horse_33.jpg', name:'Ingrid', age:8,
 species:'Norwegian Fjord', origin:'Western Norway',
 stat:['Height','13.3 hh'],
 bio:"Ninety per cent of Fjords are brown dun like me, and all of us have the dark stripe down the mane and usually down the back too. We are one of the oldest and purest breeds going. Also, we are very round.",
 tags:['Brown dun','Dorsal stripe','Pleasantly round'],
 prompt:['A compliment I will accept','“Sturdy.” Say it plainly. I am not offended.']},

{id:'h34', sex:'m', kind:'horse', img:'img/horse_34.jpg', name:'Barnaby', age:7,
 species:'Gypsy Cob', origin:'Britain & Ireland',
 stat:['Height','14.3 hh'],
 bio:"Bred by Romani families to pull the wagons — which is why I am calm, strong, and patterned like a dropped cow. I am currently leaning over a gate. I lean over this gate most days. It is my gate now.",
 tags:['Wagon-bred','Unflappable','Owns a gate'],
 prompt:['You will find me','At the gate. Always at the gate. Come to the gate.']},

{id:'h35', sex:'f', kind:'horse', img:'img/horse_35.jpg', name:'Trudi', age:9,
 species:'Haflinger', origin:'South Tyrol',
 stat:['Height','14.2 hh'],
 bio:"Mountain-bred in the Alps, which means I am sure-footed on ground that alarms everyone else. The pink halter was a gift. I have complicated feelings about the pink halter.",
 tags:['Sure-footed','Alpine','Conflicted about pink'],
 prompt:['Not to be dramatic but','I could carry you down a mountain. I am choosing not to.']},

{id:'h36', sex:'m', kind:'horse', img:'img/horse_36.jpg', name:'Eldur', age:11,
 species:'Icelandic Horse', origin:'Iceland',
 stat:['Height','13.3 hh'],
 bio:"That is a real Icelandic mountain behind me, not a backdrop. We are called horses, never ponies, and Icelanders are extremely firm about this in a way that has ended friendships.",
 tags:['Horse not pony','Volcanic backdrop','Firm on terminology'],
 prompt:['Do not call me','A pony. I am asking nicely, once.']},

{id:'h37', sex:'m', kind:'horse', img:'img/horse_37.jpg', name:'Pollock', age:6,
 species:'Knabstrupper', origin:'Denmark',
 stat:['Height','15.2 hh'],
 bio:"This is a close-up. The rest of me is also like this. Each spot is a different size, a different shape, and in a different place than it was in my last photograph, which is either growth or witchcraft.",
 tags:['Leopard complex','Abstract','Possibly witchcraft'],
 prompt:['A compliment I get a lot','“Is that a real horse?” Yes. Yes it is.']},

{id:'h38', sex:'f', kind:'horse', img:'img/horse_38.jpg', name:'Prata', age:10,
 species:'Mangalarga Marchador', origin:'Minas Gerais, Brazil',
 stat:['Height','15.1 hh'],
 bio:"Brazil's national horse, dapple grey, and the largest registered breed in the world by stud book. My gait is so even that riders have carried full cups of coffee. I do not recommend testing this with my coffee.",
 tags:['National breed','Dappled','Coffee-safe'],
 prompt:['Test me on','Anything but the coffee.']},

{id:'h39', sex:'f', kind:'horse', img:'img/horse_39.jpg', name:'Sage', age:8,
 species:'Nokota', origin:'North Dakota, USA',
 stat:['Height','14.2 hh'],
 bio:"Blue roan, descended from horses that got fenced into Theodore Roosevelt National Park by accident in the 1950s and simply carried on. Some of us trace back to Sitting Bull's herd. We are a historical clerical error and we are thriving.",
 tags:['Blue roan','Accidental survivor','Prairie-bred'],
 prompt:['My origin story','Somebody built a fence in the wrong place. Here I am.']},

{id:'h40', sex:'m', kind:'horse', img:'img/horse_40.jpg', name:'Vasily', age:12,
 species:'Orlov Trotter', origin:'Russia',
 stat:['Height','16.0 hh'],
 bio:"Founded by Count Orlov in 1776 from an Arabian stallion he acquired under circumstances nobody has ever fully explained. I trot. That is the whole discipline. I trot beautifully and at speed and I do not gallop, thank you.",
 tags:['Trots only','Imperial lineage','Suspicious origins'],
 prompt:['A boundary I hold','I will not gallop. Do not ask. We have discussed this.']},

{id:'h41', sex:'f', kind:'horse', img:'img/horse_41.jpg', name:'Bandana', age:6,
 species:'Paint Horse', origin:'Texas, USA',
 stat:['Height','15.2 hh'],
 bio:"Tobiano markings, stock build, and a registry that will not accept you unless your parents were on the list. I did not make the rules. I have benefited enormously from the rules.",
 tags:['Tobiano','Stock type','Nepotism-adjacent'],
 prompt:['I am secretly','Fine with being famous for my markings. Genuinely fine.']},

{id:'h42', sex:'m', kind:'horse', img:'img/horse_42.jpg', name:'Mambo', age:9,
 species:'Paso Fino', origin:'Puerto Rico',
 stat:['Height','14.2 hh'],
 bio:"My gait is a rapid, even four-beat step that sounds like applause on a hard road. It has three speeds and all of them are smoother than anything you have sat on. The name means “fine step”. I named myself, essentially.",
 tags:['Four-beat gait','Sounds like applause','Self-named'],
 prompt:['Put me on','Cobblestones. Then close your eyes and just listen.']},

{id:'h43', sex:'f', kind:'horse', img:'img/horse_43.jpg', name:'Huguette', age:13,
 species:'Percheron', origin:'Perche, France',
 stat:['Height','17.0 hh'],
 bio:"Grey, enormous, and in harness with my colleague, who is also called Huguette, which causes problems. Percherons are draught horses with Arabian blood, so I am both a lorry and, in certain lights, elegant.",
 tags:['Draught','Arabian blood','Naming conflict'],
 prompt:['A recurring problem in my life','Being called. Both of us come. Every time.']},

{id:'h44', sex:'m', kind:'horse', img:'img/horse_44.jpg', name:'Gobi', age:1,
 species:"Przewalski's Horse", origin:'Mongolian Steppe',
 stat:['Height','11.2 hh'],
 bio:"I am a foal and I am already a conservation success story, which is a lot of pressure for someone who cannot yet reliably find their own mother. Every one of us alive descends from about twelve individuals.",
 tags:['Foal','Endangered','Under pressure'],
 prompt:['What I need from a partner','Patience. I am one. I will step on you.']},

{id:'h45', sex:'m', kind:'horse', img:'img/horse_45.jpg', name:'Angus', age:14,
 species:'Shetland Pony', origin:'Shetland Isles',
 stat:['Height','10.1 hh'],
 bio:"Ginger, shaggy, and from an island where the weather is a personal insult. Shetlands worked down coal mines for a century, so I have a family history of being underground and resentful about it.",
 tags:['Ginger','Ex-pit pony lineage','Holds a grudge'],
 prompt:['Ask me about','The mines. Sit down first. It takes a while.']},

{id:'h46', sex:'f', kind:'horse', img:'img/horse_46.jpg', name:'Nell', age:11,
 species:'Shire', origin:'England',
 stat:['Height','17.2 hh'],
 bio:"That is my harness partner beside me. We have worked together for six years and we now move as one animal with eight legs and two opinions, which are usually the same opinion.",
 tags:['Works in a pair','White blaze','Synchronised'],
 prompt:['My closest relationship','Her. Sorry. You did ask.']},

{id:'h47', sex:'m', kind:'horse', img:'img/horse_47.jpg', name:'Nuno', age:9,
 species:'Sorraia', origin:'Sorraia Valley, Portugal',
 stat:['Height','14.1 hh'],
 bio:"There are fewer than two hundred of us in the world. Dun coat, dorsal stripe, zebra bars on the legs, and a face that matches the horses painted on cave walls in Iberia. We travel in a small, serious group.",
 tags:['Under 200 alive','Zebra leg bars','Prehistoric face'],
 prompt:['My type','Someone who understands that my whole family is also here.']},

{id:'h48', sex:'m', kind:'horse', img:'img/horse_48.jpg', name:'Beau', age:10,
 species:'Tennessee Walker', origin:'Tennessee, USA',
 stat:['Height','15.3 hh'],
 bio:"Palomino, flaxen mane, and a running walk that covers ground at ten miles an hour while nodding my head like I agree with everything you are saying. I usually do not. The nodding is involuntary.",
 tags:['Running walk','Flaxen mane','Involuntary nodding'],
 prompt:['Read me correctly','The head-nod is a gait. It is not agreement.']},

{id:'h49', sex:'f', kind:'horse', img:'img/horse_49.jpg', name:'Myfanwy', age:15,
 species:'Welsh Pony', origin:'Wales',
 stat:['Height','13.0 hh'],
 bio:"Welsh ponies have run wild on those hills since Roman times, and Henry VIII once ordered all small horses destroyed to improve the stock. We hid in the mountains. It went badly for him and well for us.",
 tags:['Outlasted a Tudor','Hill-bred','Historically stubborn'],
 prompt:['A grudge I maintain','Henry VIII. Yes, still. He started it.']},

{id:'h50', sex:'f', kind:'horse', img:'img/horse_50.jpg', name:'Lyra', age:8,
 species:'Marwari', origin:'Rajasthan, India',
 stat:['Height','15.0 hh'],
 bio:"Here they are. The tips touch, or very nearly, and they rotate a full 180 degrees independently of one another. No other horse on Earth has this. I am aware you came for the ears. Everyone comes for the ears.",
 tags:['The ears','180° rotation','Unique in the world'],
 prompt:['Look, I know why you are here','The ears. Take your time. I will wait.']},

/* ── MORE TOUCANS ─────────────────────────────────────────── */
{id:'t25', sex:'f', kind:'toucan', img:'img/toucan_25.jpg', name:'Sierra', age:6,
 species:'Grey-breasted Mountain Toucan', origin:'Peruvian Andes',
 stat:['Bill','8 cm'],
 bio:"Caught mid-berry, which is roughly eighty per cent of my waking life. I live above 2,400 metres where the trees are short, the moss is thick, and nobody has ever been warm.",
 tags:['Berry-focused','High Andes','Perpetually cold'],
 prompt:['My love language','Passing you a berry. That is the whole gesture. Do not overthink it.']},

{id:'t26', sex:'f', kind:'toucan', img:'img/toucan_26.jpg', name:'Porcelana', age:5,
 species:'Plate-billed Mountain Toucan', origin:'Andes, Ecuador',
 stat:['Bill','9 cm'],
 bio:"The yellow plate on my bill is a separate raised piece of keratin that appears to serve no function at all. I have made my peace with being decorative. It took a while.",
 tags:['Decorative plate','Cloud forest','At peace with it'],
 prompt:['Something I have accepted','Not everything needs a reason. Look at me.']},

{id:'t27', sex:'m', kind:'toucan', img:'img/toucan_27.jpg', name:'Delft', age:7,
 species:'Plate-billed Mountain Toucan', origin:'Andes, Ecuador',
 stat:['Bill','9 cm'],
 bio:"Only about 10,000 of us are left and our forest is going in slices. Still: turquoise eye skin, a red patch nobody expects, and a plate on my face. I intend to be memorable on the way through.",
 tags:['Near-threatened','Turquoise eye skin','Memorable'],
 prompt:['My philosophy','Be extremely conspicuous. It has not worked yet. I am committed.']},

{id:'t28', sex:'f', kind:'toucan', img:'img/toucan_28.jpg', name:'Tinta', age:4,
 species:'Black-billed Mountain Toucan', origin:'Colombia',
 stat:['Bill','8 cm'],
 bio:"Colombian, Andean, and turquoise across the back in a way that photographs badly and looks extraordinary in person. You will simply have to come to the Andes. I am not travelling.",
 tags:['Turquoise back','Andean','Not travelling'],
 prompt:['If you want to meet','Bogotá, then up. Bring a coat. I am not moving.']},

{id:'t29', sex:'m', kind:'toucan', img:'img/toucan_29.jpg', name:'Pistachio', age:4,
 species:'Emerald Toucanet', origin:'Mexico',
 stat:['Bill','7 cm'],
 bio:"Green body, yellow-and-black bill, blue throat, red under the tail. I look like four different birds were combined by a committee that never met. It works. Nobody knows why.",
 tags:['Committee design','Blue throat','Somehow works'],
 prompt:['A compliment that lands','“That should not go together.” Correct. And yet.']},

{id:'t30', sex:'m', kind:'toucan', img:'img/toucan_30.jpg', name:'Ridge', age:5,
 species:'Groove-billed Toucanet', origin:'Venezuela',
 stat:['Bill','7 cm'],
 bio:"Venezuelan coastal cloud forest, which is a small strip of very wet mountain that holds birds found nowhere else. I am one of them. My bill has grooves. We have been through this.",
 tags:['Endemic-ish','Grooved bill','Coastal cordillera'],
 prompt:['Ask me literally anything else','I will still bring up the grooves.']},

{id:'t31', sex:'m', kind:'toucan', img:'img/toucan_31.jpg', name:'Otávio', age:8,
 species:'Black-necked Aracari', origin:'Brazil',
 stat:['Bill','10 cm'],
 bio:"Pale yellow bill, black hood, red rump, and a bare patch of blue skin around the eye that changes shade depending on my mood. This is not a metaphor. It is genuinely a mood ring on my face.",
 tags:['Mood-ring face','Red rump','Blue eye skin'],
 prompt:['How to read me','Look at my face. The colour is the answer. It is never good news.']},

{id:'t32', sex:'m', kind:'toucan', img:'img/toucan_32.jpg', name:'Marcel', age:6,
 species:'Curl-crested Aracari', origin:'Peru',
 stat:['Bill','11 cm'],
 bio:"These curls are flattened, hardened, glossy black plates — closer to plastic than to feathers. Nobody knows what they are for. I have been asked about my hair every day of my adult life.",
 tags:['Plastic curls','Unexplained','Asked daily'],
 prompt:['The question I am tired of','“Is that real?” It is attached to my head. Draw your own conclusions.']},

{id:'t33', sex:'f', kind:'toucan', img:'img/toucan_33.jpg', name:'Ondina', age:5,
 species:'Curl-crested Aracari', origin:'Peru',
 stat:['Bill','11 cm'],
 bio:"Western Amazonia, south of the river, in the canopy where the fig trees are. I travel in a group of eight and we sleep in a single hollow. The curls do not help with that. The curls have never helped with anything.",
 tags:['Canopy-dweller','Group of eight','Impractical hair'],
 prompt:['My honest assessment','Beautiful hair, structurally useless. Like most beautiful things.']},

{id:'t34', sex:'m', kind:'toucan', img:'img/toucan_34.jpg', name:'Mamão', age:6,
 species:'Chestnut-eared Aracari', origin:'Bolivia',
 stat:['Bill','11 cm'],
 bio:"Photographed beside a papaya, which is not a coincidence. I have located every fruiting tree within four square kilometres and I maintain the list mentally. Ask me anything about fruit.",
 tags:['Fruit cartographer','Papaya-adjacent','Encyclopaedic'],
 prompt:['My specialist subject','Which tree is ripe. When. I am never wrong about this.']},

{id:'t35', sex:'m', kind:'toucan', img:'img/toucan_35.jpg', name:'Bolívar', age:7,
 species:'Chestnut-eared Aracari', origin:'Bolivia',
 stat:['Bill','11 cm'],
 bio:"Against a clear sky for once, which almost never happens because I live in the understorey. The red belly band, the chestnut ear patch, the yellow — all of it is much louder in daylight and I regret nothing.",
 tags:['Belly band','Understorey resident','Loud in daylight'],
 prompt:['A rare event','Me, visible, against the sky. Enjoy it. It will not last.']},

{id:'t36', sex:'m', kind:'toucan', img:'img/toucan_36.jpg', name:'Glyph', age:5,
 species:'Lettered Aracari', origin:'Amazonia',
 stat:['Bill','9 cm'],
 bio:"Smallest aracari in the Amazon, and the black scratches on my bill genuinely do look like a signature. Male bills carry more of it than female ones, so technically I am the more heavily annotated sex.",
 tags:['Annotated bill','Smallest aracari','Sexually dimorphic'],
 prompt:['A fun fact I deploy at parties','My face has more writing on it than yours does.']},

{id:'t37', sex:'f', kind:'toucan', img:'img/toucan_37.jpg', name:'Ribbon', age:6,
 species:'Many-banded Aracari', origin:'Ecuador',
 stat:['Bill','11 cm'],
 bio:"Two black bands across a yellow belly, which is one more band than most of my relatives manage and I do bring it up. Western Amazon, upper canopy, generally shouting.",
 tags:['Two bands','Upper canopy','Generally shouting'],
 prompt:['My competitive streak','One more band. That is it. That is the whole rivalry.']},

{id:'t38', sex:'m', kind:'toucan', img:'img/toucan_38.jpg', name:'Tulio', age:5,
 species:'Collared Aracari', origin:'Panama',
 stat:['Bill','10 cm'],
 bio:"Central American, communal, and extremely involved in other birds' business. Up to six adults help raise one brood, which sounds heartwarming until you have sat through the discussions.",
 tags:['Co-operative breeder','Nosy','Committee-based'],
 prompt:['Something that drains me','Group decisions. Six opinions. One nest hole.']},

{id:'t39', sex:'f', kind:'toucan', img:'img/toucan_39.jpg', name:'Absinthe', age:4,
 species:'Green Aracari', origin:'Suriname',
 stat:['Bill','9 cm'],
 bio:"On the ground, briefly, which is unusual and slightly embarrassing for a canopy bird. I am the smallest toucan there is. Please do not mention the ground thing.",
 tags:['Smallest toucan','Rarely grounded','Embarrassed'],
 prompt:['We are not discussing','The photograph. Moving on.']},

{id:'t40', sex:'m', kind:'toucan', img:'img/toucan_40.jpg', name:'Pantone', age:6,
 species:'Keel-billed Toucan', origin:'Costa Rica',
 stat:['Bill','15 cm'],
 bio:"My bill is green at the base, orange along the side, red at the tip and blue underneath, and it weighs almost nothing because it is mostly hollow struts and air. Structurally, I am a very colourful sponge.",
 tags:['Four-colour bill','Hollow struts','Colourful sponge'],
 prompt:['I am basically','Load-bearing foam. Do not tell anyone.']},

{id:'t41', sex:'f', kind:'toucan', img:'img/toucan_41.jpg', name:'Dulce', age:7,
 species:'Yellow-throated Toucan', origin:'Costa Rica',
 stat:['Bill','15 cm'],
 bio:"Largest toucan in Central America and loud enough to be heard from the next valley. I swallow fruit whole and regurgitate the seed some distance away, which makes me both a diner and a delivery service.",
 tags:['Largest in region','Seed delivery','Carrying voice'],
 prompt:['My side hustle','Reforestation. Unpaid. Ongoing. Involuntary.']},

{id:'t42', sex:'m', kind:'toucan', img:'img/toucan_42.jpg', name:'Sol', age:5,
 species:'Yellow-throated Toucan', origin:'Costa Rica',
 stat:['Bill','14 cm'],
 bio:"Sharing a branch with a bromeliad, which holds its own private pool of rainwater with frogs living in it. My entire neighbourhood is like this. Everything here contains something else.",
 tags:['Bromeliad neighbour','Rainforest','Nested ecosystems'],
 prompt:['Something that amazes me daily','There are frogs in that plant. Frogs. In the plant.']},

{id:'t43', sex:'f', kind:'toucan', img:'img/toucan_43.jpg', name:'Chuva', age:6,
 species:'Chocó Toucan', origin:'Chocó, Ecuador',
 stat:['Bill','14 cm'],
 bio:"I am restricted to a narrow wet strip between the Andes and the Pacific, which is one of the most biodiverse places on the planet and also one of the fastest-disappearing. No pressure on either of us.",
 tags:['Range-restricted','Biodiversity hotspot','Quietly worried'],
 prompt:['A thought I keep having','There used to be more forest. That is the whole thought.']},

{id:'t44', sex:'f', kind:'toucan', img:'img/toucan_44.jpg', name:'Granada', age:8,
 species:'Red-breasted Toucan', origin:'Atlantic Forest, Brazil',
 stat:['Bill','12 cm'],
 bio:"Orange-yellow throat running into a red band across the chest, which reads as a very confident waistcoat. Atlantic Forest resident, which means I live in the seven per cent of it that is left.",
 tags:['Confident waistcoat','Atlantic Forest','Seven per cent'],
 prompt:['My wardrobe','One waistcoat. Worn daily. Never removed. Committed.']},

{id:'t45', sex:'f', kind:'toucan', img:'img/toucan_45.jpg', name:'Jussara', age:6,
 species:'Red-breasted Toucan', origin:'Atlantic Forest, Brazil',
 stat:['Bill','12 cm'],
 bio:"Hanging upside down in a palm because the fruit is down there and dignity is a luxury. Toucans like me are the main reason juçara palms still spread — the seeds have to go through a bird this size.",
 tags:['Upside down','Palm specialist','Ecologically essential'],
 prompt:['My job description','Eat the fruit. Fly away. Produce a tree. Repeat.']},

{id:'t46', sex:'m', kind:'toucan', img:'img/toucan_46.jpg', name:'Tuca', age:9,
 species:'Toco Toucan', origin:'Pantanal, Brazil',
 stat:['Bill','19 cm'],
 bio:"The name “toucan” comes from Tupi, and so does mine, more or less. I am the one everyone pictures: black body, white bib, absurd orange bill. I am the default toucan and I carry that professionally.",
 tags:['The default toucan','Tupi name','Professional'],
 prompt:['My burden','Being the one on the cereal box. Everyone expects things.']},

{id:'t47', sex:'f', kind:'toucan', img:'img/toucan_47.jpg', name:'Pérola', age:7,
 species:'White-throated Toucan', origin:'Guyana',
 stat:['Bill','17 cm'],
 bio:"Two of us on one branch, which is either a pair bond or a dispute and it is genuinely hard to tell from outside. Toucans court by throwing fruit at each other, so the line is thin.",
 tags:['In a pair, probably','Fruit-throwing courtship','Ambiguous'],
 prompt:['Our relationship status','Under negotiation. Fruit has been thrown. Interpretations differ.']},

{id:'t48', sex:'f', kind:'toucan', img:'img/toucan_48.jpg', name:'Monstera', age:5,
 species:'Channel-billed Toucan', origin:'Amazonia',
 stat:['Bill','13 cm'],
 bio:"Beside a leaf roughly the size of me, which puts the whole rainforest into perspective. The grooves along my bill are called channels and they run the full length. Everything here is bigger than it needs to be.",
 tags:['Dwarfed by a leaf','Channelled bill','Sense of scale'],
 prompt:['Something I think about','Why is the leaf that big. Why is anything that big.']},

{id:'t49', sex:'m', kind:'toucan', img:'img/toucan_49.jpg', name:'Aurelio', age:6,
 species:'Golden-collared Toucanet', origin:'Peru',
 stat:['Bill','8 cm'],
 bio:"Thin gold collar, black hood, olive body, and a red patch at the rear that only appears when I turn around. I am designed to be revealed gradually. It is exhausting for everyone.",
 tags:['Gold collar','Hidden red','Gradual reveal'],
 prompt:['How to appreciate me','Slowly. From several angles. Bring time.']},

/* ── COWS ─────────────────────────────────────────────────── */
{id:'c00', sex:'f', kind:'cow', img:'img/cow_00.jpg', name:'Miep', age:6,
 species:'Holstein Friesian', origin:'Friesland, Netherlands',
 stat:['Weight','680 kg'],
 bio:"I am the cow you pictured when you read the word cow, and I have made my peace with being the default. Every black patch on me is a different shape and I have never once been asked about it.",
 tags:['The default cow','Patchwork','Quietly iconic'],
 prompt:['What I want you to know','There are other cows. I am simply the one you thought of.']},

{id:'c01', sex:'f', kind:'cow', img:'img/cow_01.jpg', name:'Pansy', age:5,
 species:'Jersey', origin:'Jersey, Channel Islands',
 stat:['Weight','450 kg'],
 bio:"Small, fawn and in possession of eyelashes that have caused at least one traffic incident. My milk is the richest there is, which I mention early so we both know where we stand.",
 tags:['Enormous eyelashes','Very rich milk','Small but aware'],
 prompt:['My love language','Being looked at, at length, by someone leaning on a gate.']},

{id:'c02', sex:'f', kind:'cow', img:'img/cow_02.jpg', name:'Winnie', age:8,
 species:'Guernsey', origin:'Guernsey, Channel Islands',
 stat:['Weight','500 kg'],
 bio:"My milk comes out faintly golden and I have dined out on that fact for eight years. I am from the other island, the one people forget, and I would rather not discuss Jersey at all.",
 tags:['Golden milk','The other island','Long-running grudge'],
 prompt:['Do not ask me about','Jersey. Any of it. The cows, the island, the jumper.']},

{id:'c03', sex:'f', kind:'cow', img:'img/cow_03.jpg', name:'Vreni', age:7,
 species:'Brown Swiss', origin:'Canton of Schwyz, Switzerland',
 stat:['Weight','600 kg'],
 bio:"Mouse-grey, mountain-bred and fitted with a bell I did not consent to. I have walked up the same alp every June since I could walk and I could do it now with my eyes shut, which some mornings I do.",
 tags:['Alpine commute','Unconsented bell','Grey as weather'],
 prompt:['My annual highlight','Coming back down in September wearing flowers, like a returning general.']},

{id:'c04', sex:'m', kind:'cow', img:'img/cow_04.jpg', name:'Gus', age:9,
 species:'Hereford', origin:'Herefordshire, England',
 stat:['Weight','1000 kg'],
 bio:"White face, red everything else, and a build best described as agricultural. I was invented in a damp English county and somehow ended up in west Texas, where nobody has ever mentioned the climate difference to me.",
 tags:['White face','Built like a shed','Relocated'],
 prompt:['Two truths and a lie','I am from England. I live in Texas. I have adjusted.']},

{id:'c05', sex:'m', kind:'cow', img:'img/cow_05.jpg', name:'Blanchard', age:7,
 species:'Charolais', origin:'Charolles, France',
 stat:['Weight','1100 kg'],
 bio:"Entirely cream-coloured, entirely enormous, and entirely uninterested in your fence. I am told I have presence, which is a polite French way of saying I am difficult to walk around.",
 tags:['Cream all over','Eleven hundred kilos','Presence'],
 prompt:['The compliment I get most','That I look like something carved rather than born.']},

{id:'c06', sex:'f', kind:'cow', img:'img/cow_06.jpg', name:'Cerise', age:4,
 species:'Limousin', origin:'Limousin, France',
 stat:['Weight','700 kg'],
 bio:"Golden-red from nose to tail, with a fringe that grows into my eyes every winter and nobody does anything about it. I come from a part of France where the granite is the same colour as me and I take that personally.",
 tags:['Golden-red','Winter fringe','Colour-matched to geology'],
 prompt:['My simple pleasures','Standing in low sun so the whole field has to look at me.']},

{id:'c07', sex:'f', kind:'cow', img:'img/cow_07.jpg', name:'Seline', age:6,
 species:'Simmental', origin:'Simme Valley, Switzerland',
 stat:['Weight','750 kg'],
 bio:"Red and white in a pattern that took nine hundred years of Swiss valley breeding to arrive at, and I wear it to agricultural shows. There is a photograph of my head from 2017 that has done rather well for itself.",
 tags:['Nine centuries of design','Show circuit','Mildly famous head'],
 prompt:['How to appreciate me','From the side. The three-quarter angle is where the work shows.']},

{id:'c08', sex:'f', kind:'cow', img:'img/cow_08.jpg', name:'Morag', age:11,
 species:'Highland', origin:'Scottish Highlands',
 stat:['Weight','500 kg'],
 bio:"I am ninety per cent fringe and I see the world as an orange blur, which has never once been a problem. My coat is two coats, the underneath one is waterproof, and I have no opinion on summer.",
 tags:['Ninety per cent fringe','Double coat','Weatherproof'],
 prompt:['The question I always get','Whether I can see. The answer is enough.']},

{id:'c09', sex:'f', kind:'cow', img:'img/cow_09.jpg', name:'Maisie', age:5,
 species:'Belted Galloway', origin:'Galloway, Scotland',
 stat:['Weight','450 kg'],
 bio:"Black at both ends with one broad white band around the middle, like something that came in packaging. Children call me the Oreo cow and I have stopped correcting them because I have no better suggestion.",
 tags:['Comes with a belt','The Oreo thing','No better suggestion'],
 prompt:['Something nobody knows about me','Under all of this I am extremely shaggy and extremely warm.']},

{id:'c10', sex:'f', kind:'cow', img:'img/cow_10.jpg', name:'Junebug', age:8,
 species:'Texas Longhorn', origin:'Texas, USA',
 stat:['Weight','600 kg'],
 bio:"My horns measure further across than I am long, which makes gateways a matter of geometry and patience. I am speckled brown on white in a pattern no other cow has, because no two of us have ever matched.",
 tags:['Horns wider than me','One-off pattern','Geometry problems'],
 prompt:['My greatest skill','Getting through a gate I do not fit through. It takes forty minutes.']},

{id:'c11', sex:'f', kind:'cow', img:'img/cow_11.jpg', name:'Marigold', age:6,
 species:'Brahman', origin:'Texas, USA',
 stat:['Weight','550 kg'],
 bio:"Ash-grey, loose-skinned, with ears that hang like they are disappointed and a hump I did not ask for. The hump is storage, the skin is air conditioning, and the ears are just how it went.",
 tags:['Hump storage','Skin air conditioning','Disappointed ears'],
 prompt:['What I am best at','Heat. Simply not minding it. It is my entire personality.']},

{id:'c12', sex:'f', kind:'cow', img:'img/cow_12.jpg', name:'Lalita', age:7,
 species:'Gir', origin:'Gujarat, India',
 stat:['Weight','475 kg'],
 bio:"My forehead is a dome, my ears are folded like envelopes, and my horns go backwards, which surprises people who have only met ordinary cows. I was born in Gujarat and now live in Mexico, and neither place has explained this to me.",
 tags:['Domed forehead','Envelope ears','Backwards horns'],
 prompt:['The question I always get','Why my ears do that. Nobody has ever known.']},

{id:'c13', sex:'m', kind:'cow', img:'img/cow_13.jpg', name:'Ercole', age:6,
 species:'Chianina', origin:'Val di Chiana, Italy',
 stat:['Weight','1300 kg'],
 bio:"I am the largest breed of cattle on the planet and porcelain white all over, which is a combination that makes barns feel small. The Romans sacrificed my ancestors because we looked appropriately significant, and I have never fully relaxed since.",
 tags:['Largest on earth','Porcelain white','Historically significant'],
 prompt:['My simple pleasures','Walking into a building and watching everyone recalculate.']},

{id:'c14', sex:'f', kind:'cow', img:'img/cow_14.jpg', name:'Lotte', age:1,
 species:'Glan', origin:'Rhineland-Palatinate, Germany',
 stat:['Weight','120 kg'],
 bio:"I am ten days old in this photograph and everything is new, including grass, which I have decided against. My mother is somewhere behind me and I am pretending this was my own idea.",
 tags:['Ten days old','Anti-grass','Pretending'],
 prompt:['My simple pleasures','Standing up. Every time. It has not got old yet.']},

{id:'c15', sex:'f', kind:'cow', img:'img/cow_15.jpg', name:'Fiorella', age:5,
 species:'Marchigiana', origin:'Marche, Italy',
 stat:['Weight','700 kg'],
 bio:"Pale grey shading to white, with black skin underneath that stops me burning in an Italian summer nobody warned me about. I am wearing a red show halter in this picture and I would like it noted that I did not choose it.",
 tags:['Grey over black','Sun-proofed','Halter grievance'],
 prompt:['Do not ask me about','The halter. It was a whole thing.']},

{id:'c16', sex:'f', kind:'cow', img:'img/cow_16.jpg', name:'Adriana', age:9,
 species:'Romagnola', origin:'Romagna, Italy',
 stat:['Weight','750 kg'],
 bio:"White coat, black nose, horns that curve forward like brackets around a sentence I never finish. I have been lying in this exact spot since Tuesday and I intend to see the week out here.",
 tags:['Bracket horns','Committed to the spot','Slow week'],
 prompt:['My ideal day','Identical to yesterday, in the same place, at the same angle.']},

{id:'c17', sex:'f', kind:'cow', img:'img/cow_17.jpg', name:'Selva', age:10,
 species:'Maremmana', origin:'Maremma, Italy',
 stat:['Weight','650 kg'],
 bio:"Steel grey with lyre-shaped horns, bred to walk through Tuscan scrub that other cattle simply refuse to enter. My people were herded by mounted cowboys called butteri, which is a fact I deploy whenever anyone mentions Texas.",
 tags:['Lyre horns','Scrubland specialist','Italian cowboys'],
 prompt:['The fact I always mention','Italy had cowboys first. I will not be drawn further.']},

{id:'c18', sex:'f', kind:'cow', img:'img/cow_18.jpg', name:'Rosaria', age:8,
 species:'Podolica', origin:'Basilicata, Italy',
 stat:['Weight','550 kg'],
 bio:"I live half-wild in the southern hills and produce very little milk, all of which becomes a cheese people queue for. My calf is fawn-coloured now and will turn grey like me, which nobody has told him yet.",
 tags:['Half-wild','Queued-for cheese','Undisclosed colour change'],
 prompt:['Something nobody knows about me','Every one of us is born the wrong colour. We grow into it.']},

{id:'c19', sex:'f', kind:'cow', img:'img/cow_19.jpg', name:'Odette', age:6,
 species:'Aubrac', origin:'Aveyron, France',
 stat:['Weight','650 kg'],
 bio:"Wheat-coloured with black eyeliner I was born wearing and horns that lift like a pair of raised eyebrows. I spend summers on a high plateau where the weather is an opinion rather than a forecast.",
 tags:['Born with eyeliner','Eyebrow horns','High plateau'],
 prompt:['My love language','Eye contact, held slightly too long, from forty metres away.']},

{id:'c20', sex:'f', kind:'cow', img:'img/cow_20.jpg', name:'Bernadette', age:7,
 species:'Gascon', origin:'Gascony, France',
 stat:['Weight','700 kg'],
 bio:"Silver-grey with a black muzzle and the general air of someone who has been to the Pyrenees and found them adequate. I am at an agricultural fair in this photograph and the people behind me are not with me.",
 tags:['Silver-grey','Pyrenean standards','Not with them'],
 prompt:['Do not ask me about','The crowd. I was there first.']},

{id:'c21', sex:'f', kind:'cow', img:'img/cow_21.jpg', name:'Hortense', age:9,
 species:'Normande', origin:'Normandy, France',
 stat:['Weight','700 kg'],
 bio:"Brown, white and brindled, with dark rings round both eyes that make me look permanently unimpressed by Normandy. My milk goes into Camembert, so in a sense I have already peaked and I am fine about it.",
 tags:['Spectacled','Brindled','Peaked early'],
 prompt:['How to appreciate me','On a cheeseboard, ideally, and at room temperature.']},

{id:'c22', sex:'f', kind:'cow', img:'img/cow_22.jpg', name:'Amandine', age:5,
 species:'Vosgienne', origin:'Vosges, France',
 stat:['Weight','650 kg'],
 bio:"Black with a white stripe down my spine and a white face, like something that was dipped rather than born. There are not many of us left, which makes every photograph feel like a bit of an occasion.",
 tags:['Dipped, not born','Spinal stripe','Rare occasion'],
 prompt:['What I want you to know','There are under three thousand of me. Choose accordingly.']},

{id:'c23', sex:'f', kind:'cow', img:'img/cow_23.jpg', name:'Resi', age:8,
 species:'Tyrolean Grey', origin:'Tyrol, Austria',
 stat:['Weight','550 kg'],
 bio:"Silver at the shoulders shading darker towards the back, which the breed society calls a gradient and I call Tuesday. I wear a bell the size of a bucket and I can hear myself thinking only in the winter shed.",
 tags:['Silver gradient','Bucket-sized bell','Winter quiet'],
 prompt:['My ideal day','Anywhere the bell does not echo. A meadow. A wide one.']},

{id:'c24', sex:'f', kind:'cow', img:'img/cow_24.jpg', name:'Brigid', age:7,
 species:'Dexter', origin:'County Kerry, Ireland',
 stat:['Weight','350 kg'],
 bio:"I am the smallest cattle breed in Europe and I fit through gaps that were not designed as gaps. People consistently mistake me for a calf, which I allow to continue because it lowers expectations wonderfully.",
 tags:['Smallest in Europe','Fits through gaps','Low expectations'],
 prompt:['My greatest skill','Being underestimated. It gets me into the good field.']},

{id:'c25', sex:'m', kind:'cow', img:'img/cow_25.jpg', name:'Cormac', age:1,
 species:'Kerry', origin:'County Kerry, Ireland',
 stat:['Weight','180 kg'],
 bio:"Entirely black, entirely new, and standing in what I have been told is a field but strongly suspect is weather. My breed is one of the oldest in Europe and I have been given no instructions about that whatsoever.",
 tags:['Entirely black','Ancient lineage','No instructions'],
 prompt:['Two truths and a lie','This is a field. I am ancient. I know what I am doing.']},

{id:'c26', sex:'f', kind:'cow', img:'img/cow_26.jpg', name:'Saoirse', age:6,
 species:'Irish Moiled', origin:'County Antrim, Ireland',
 stat:['Weight','600 kg'],
 bio:"White with red flecks and absolutely no horns, which is the whole point of me — moiled means bald. There were about thirty of us left in the nineteen seventies, so I take the long view on most things.",
 tags:['Deliberately hornless','Red-flecked','Nearly gone once'],
 prompt:['What I want you to know','We got down to thirty. Everything since then is extra.']},

{id:'c27', sex:'f', kind:'cow', img:'img/cow_27.jpg', name:'Snowdrop', age:1,
 species:'British White', origin:'Norfolk, England',
 stat:['Weight','60 kg'],
 bio:"Newborn, white all over, with black ears, black nose and black eyelids as though I were finished by a careful person. I am several hours old in this picture and already the mud has found me.",
 tags:['Several hours old','Black trim','Already muddy'],
 prompt:['My simple pleasures','Legs. Having four. Using them in roughly the right order.']},

{id:'c28', sex:'f', kind:'cow', img:'img/cow_28.jpg', name:'Poppy', age:2,
 species:'Red Poll', origin:'Suffolk, England',
 stat:['Weight','600 kg'],
 bio:"Deep red, no horns, and from a county so flat that I can see everyone approaching for a full twenty minutes. I do both milk and beef, which in Suffolk is considered showing off.",
 tags:['Hornless','Dual-purpose','Flat horizons'],
 prompt:['Do not ask me about','Which one I am better at. That is the whole Suffolk question.']},

{id:'c29', sex:'f', kind:'cow', img:'img/cow_29.jpg', name:'Bramble', age:7,
 species:'Sussex', origin:'Sussex, England',
 stat:['Weight','650 kg'],
 bio:"A deep chestnut red that goes almost purple in the rain, which in Sussex is most of the year. My ancestors pulled ploughs across the Weald and I have inherited the shoulders without any of the work.",
 tags:['Purple when wet','Plough shoulders','No actual ploughing'],
 prompt:['Something nobody knows about me','These shoulders are entirely decorative now. I have kept them anyway.']},

{id:'c30', sex:'f', kind:'cow', img:'img/cow_30.jpg', name:'Paloma', age:6,
 species:'Corriente', origin:'Northern Mexico',
 stat:['Weight','450 kg'],
 bio:"Descended from the first cattle Spain ever landed in the Americas, which is five centuries of not being caught. I am small, quick and horned, and I have a white speckled belly that only shows when I am already gone.",
 tags:['Five centuries feral','Quick','Speckled underneath'],
 prompt:['My greatest skill','Being elsewhere by the time anyone has decided to do something about me.']},

{id:'c31', sex:'f', kind:'cow', img:'img/cow_31.jpg', name:'Godelieve', age:5,
 species:'Belgian Blue', origin:'Wallonia, Belgium',
 stat:['Weight','750 kg'],
 bio:"Blue roan, extremely muscled, and the subject of a great many double takes at the fence. I did not do this at the gym, it is a gene, and I would rather talk about almost anything else.",
 tags:['Blue roan','It is a gene','Double takes'],
 prompt:['Do not ask me about','The muscles. It is genetic and the conversation never goes anywhere good.']},

{id:'c32', sex:'f', kind:'cow', img:'img/cow_32.jpg', name:'Solange', age:8,
 species:"Blonde d'Aquitaine", origin:'Aquitaine, France',
 stat:['Weight','900 kg'],
 bio:"Wheat-blonde, very long in the body, and built along lines that the French describe as harmonious. I have a calf with me somewhere in this field and he is the same colour as the grass in August, which is inconvenient.",
 tags:['Wheat-blonde','Harmonious lines','Camouflaged offspring'],
 prompt:['My ideal day','August. Long grass. Knowing roughly where everyone is.']},

{id:'c33', sex:'f', kind:'cow', img:'img/cow_33.jpg', name:'Yuzu', age:5,
 species:'Japanese Black', origin:'Hyōgo, Japan',
 stat:['Weight','700 kg'],
 bio:"Small, black and from the Tajima line, which is a sentence that makes certain people behave very strangely around me. I am aware of what I am famous for and I would prefer we simply enjoyed the mountains.",
 tags:['Tajima line','Aware of the reputation','Prefers the mountains'],
 prompt:['Do not ask me about','What I am famous for. Look at the view instead.']},

{id:'c34', sex:'m', kind:'cow', img:'img/cow_34.jpg', name:'Rukundo', age:9,
 species:'Ankole-Watusi', origin:'Great Lakes, Africa',
 stat:['Weight','600 kg'],
 bio:"My horns span over two metres and are full of blood vessels that cool me down, so they are not decoration, they are plumbing. They are also, obviously, decoration.",
 tags:['Two-metre horns','Structural plumbing','Also decorative'],
 prompt:['The question I always get','Whether they are heavy. They are hollow. Next question.']},

{id:'c35', sex:'f', kind:'cow', img:'img/cow_35.jpg', name:'Roselle', age:7,
 species:'Santa Gertrudis', origin:'Texas, USA',
 stat:['Weight','700 kg'],
 bio:"Cherry red, part Brahman and part Shorthorn, and the first cattle breed the United States ever made from scratch. I was invented on a ranch the size of a small country and I carry myself accordingly.",
 tags:['Cherry red','First American breed','Ranch the size of a country'],
 prompt:['What I want you to know','I was designed. On purpose. By a committee that got it right.']},

{id:'c36', sex:'f', kind:'cow', img:'img/cow_36.jpg', name:'Aino', age:6,
 species:'Finnish Ayrshire', origin:'Finland',
 stat:['Weight','550 kg'],
 bio:"Red and white, standing by a road in Sipoo, watching a car that has slowed down more than necessary. Finnish summers are four weeks long and I intend to be outdoors for every hour of them.",
 tags:['Red and white','Roadside presence','Four-week summer'],
 prompt:['My ideal day','All of it light. That happens here, briefly, and then it does not.']},

{id:'c37', sex:'m', kind:'cow', img:'img/cow_37.jpg', name:'Csaba', age:10,
 species:'Hungarian Grey', origin:'Hungarian Plain',
 stat:['Weight','800 kg'],
 bio:"Ash-white with enormous upswept horns, bred on the great plain to walk to market under my own power — sometimes as far as Nuremberg. I am now mostly a national symbol, which involves considerably less walking.",
 tags:['Upswept horns','Walked to Nuremberg','National symbol'],
 prompt:['Something nobody knows about me','My ancestors walked to Germany. To be sold. On foot. Every year.']},

{id:'c38', sex:'m', kind:'cow', img:'img/cow_38.jpg', name:'Mirko', age:11,
 species:'Istrian', origin:'Istria, Croatia',
 stat:['Weight','900 kg'],
 bio:"Pale grey, vast, and known locally as boškarin, which sounds friendlier than I am first thing in the morning. I pulled carts and ploughs for three thousand years and then tractors arrived and nobody consulted me.",
 tags:['Boškarin','Three thousand years of work','Made redundant'],
 prompt:['Do not ask me about','Tractors. I have said what I have to say about tractors.']},

{id:'c39', sex:'m', kind:'cow', img:'img/cow_39.jpg', name:'Thaddeus', age:8,
 species:'Randall Lineback', origin:'Vermont, USA',
 stat:['Weight','700 kg'],
 bio:"White with a dark speckled mantle down both sides and a clean white stripe along the spine, like a saddle that was applied rather than worn. In 1985 there were fewer than twenty of us and we all came from one farm.",
 tags:['Applied saddle','Speckled mantle','Down to twenty once'],
 prompt:['What I want you to know','One herd. One farm. Everything since is borrowed time and good luck.']},

{id:'c40', sex:'f', kind:'cow', img:'img/cow_40.jpg', name:'Noori', age:7,
 species:'Tharparkar', origin:'Sindh, Pakistan',
 stat:['Weight','400 kg'],
 bio:"White, humped, and bred in the Thar desert where the rule is simple: produce milk on almost nothing, or do not bother. I can go a long way between drinks and I would rather you did not test this.",
 tags:['Desert dairy','Runs on nothing','Do not test it'],
 prompt:['My greatest skill','Thriving on an amount of water that other cattle regard as an insult.']},

{id:'c41', sex:'f', kind:'cow', img:'img/cow_41.jpg', name:'Ursel', age:9,
 species:'Heck', origin:'Munich, Germany',
 stat:['Weight','600 kg'],
 bio:"I was bred backwards, on purpose, to resemble the aurochs — the wild cattle that died out in Poland in 1627. Opinions differ on how close they got, and I have never been shown a photograph of the original for comparison.",
 tags:['Bred backwards','Aurochs-adjacent','No reference photo'],
 prompt:['The question I always get','Whether it worked. Nobody alive can actually say.']},

{id:'c42', sex:'f', kind:'cow', img:'img/cow_42.jpg', name:'Jurema', age:6,
 species:'Caracu', origin:'Minas Gerais, Brazil',
 stat:['Weight','500 kg'],
 bio:"Solid tawny-orange, descended from Portuguese cattle that arrived four hundred years ago and simply got on with it. I handle heat, ticks and long walks, and I am told this makes me unglamorous, which I dispute.",
 tags:['Tawny-orange','Four centuries in','Disputes the charge'],
 prompt:['Do not ask me about','Whether I am glamorous. I am orange. Draw your own conclusions.']},

{id:'c43', sex:'f', kind:'cow', img:'img/cow_43.jpg', name:'Femke', age:7,
 species:'Groningen White-Headed', origin:'Groningen, Netherlands',
 stat:['Weight','650 kg'],
 bio:"Black body, white head, and the Dutch call me blaarkop, which means blister head and is not the compliment it could have been. I am a rare breed now, largely because I was never the most productive cow in the shed and everyone knew it.",
 tags:['Blister head','Black and white, but organised','Never the most productive'],
 prompt:['Do not ask me about','The name. I did not pick it and I would not have picked it.']},

{id:'c44', sex:'f', kind:'cow', img:'img/cow_44.jpg', name:'Truus', age:8,
 species:'Dutch Belted', origin:'Netherlands',
 stat:['Weight','600 kg'],
 bio:"Black at both ends with one white band around the middle, which the Dutch have been arranging deliberately since the seventeenth century. Yes, I know about the Belted Galloway. We do not discuss it.",
 tags:['Deliberate since the 1600s','One white band','Ongoing dispute'],
 prompt:['Do not ask me about','The Scottish ones. They came later. That is all I will say.']},

{id:'c45', sex:'f', kind:'cow', img:'img/cow_45.jpg', name:'Liesel', age:9,
 species:'Rotes Höhenvieh', origin:'Hesse, Germany',
 stat:['Weight','650 kg'],
 bio:"Uniformly red with pale horns, from the German uplands, and very nearly extinct by 1980 before somebody went looking. I now spend my days conservation-grazing a floodplain, which means eating in a way that counts as a job.",
 tags:['Uniformly red','Nearly gone by 1980','Eating professionally'],
 prompt:['My ideal day','Wet meadow, no schedule, and my grazing described as ecological work.']},

{id:'c46', sex:'f', kind:'cow', img:'img/cow_46.jpg', name:'Fleurette', age:6,
 species:'Evolène', origin:'Valais, Switzerland',
 stat:['Weight','500 kg'],
 bio:"Red-brown with a white back and short forward horns, from a valley where the cows settle their own hierarchy by pushing. There are a few hundred of us and every one is on a list somewhere in Bern.",
 tags:['Settles it by pushing','White-backed','On a list in Bern'],
 prompt:['My greatest skill','Determining rank in a herd without anyone getting genuinely hurt.']},

{id:'c47', sex:'f', kind:'cow', img:'img/cow_47.jpg', name:'Chitra', age:5,
 species:'Rathi', origin:'Rajasthan, India',
 stat:['Weight','350 kg'],
 bio:"Brown and white patched, from the Thar's edge, and named after the Rath people who kept us long before anyone wrote it down. I produce a genuinely unreasonable amount of milk for my size and desert.",
 tags:['Patched brown and white','Named for the Raths','Unreasonable output'],
 prompt:['What I want you to know','Look at the size of me, then look at the yield. Nobody can explain it.']},

{id:'c48', sex:'f', kind:'cow', img:'img/cow_48.jpg', name:'Adelina', age:7,
 species:'Barrosã', origin:'Minho, Portugal',
 stat:['Weight','500 kg'],
 bio:"My horns are absurd — they curve up and inwards like a lyre and they are wider than my entire head. I am from the green north of Portugal, where the horns are the point and nobody pretends otherwise.",
 tags:['Absurd lyre horns','Green north','The horns are the point'],
 prompt:['How to appreciate me','Front on. It is the only angle where the horns make sense.']},

{id:'c49', sex:'m', kind:'cow', img:'img/cow_49.jpg', name:'Beltrán', age:10,
 species:'Tudanca', origin:'Cantabria, Spain',
 stat:['Weight','600 kg'],
 bio:"Dark grey going to black at the shoulders, with horns that sweep out and up and arrive before I do. I live half-wild in the Cantabrian mountains and come down only when the weather makes the argument for me.",
 tags:['Horns arrive first','Half-wild','Comes down under protest'],
 prompt:['My ideal day','High up, low cloud, and nobody attempting to count me.']},

/* ── AND ONE OTHER THING ──────────────────────────────────── */
{id:'u00', sex:'m', kind:'horse', mythical:true, img:'img/unicorn.jpg', name:'Steve', age:1200,
 species:'Unicorn', origin:'Allegedly Avalon',
 stat:['Horn','31 cm'],
 bio:"A real unicorn. Twelve hundred years old, one wish granted per millennium, and I have already used this millennium's on something I would rather not get into. Currently residing in a stable for tax reasons.",
 tags:['Mythical','Grants wishes (rarely)','Tax arrangement'],
 prompt:['The question I always get','Whether the horn is glued on. It is not. Next question.']},
];
