/* Hoofbill — tradução pt-BR. Nomes próprios não são traduzidos. */
const PT = {
ui:{
  tagline:'cascos e bicos', everyone:'Todos', horses:'🐴 Cavalos', toucans:'🦜 Tucanos',
  deck:'Baralho', menagerie:'Meu Zoo', guide:'Guia de Campo',
  menagerieTitle:'Meu Zoo', guideTitle:'Guia de Campo Completo',
  kept:'no zoo', keptPlural:'no zoo',
  profilesTap:'perfis · toque para ler',
  smitten:'Amei', notToday:'Hoje não',
  tapMore:'toque para ler o resto',
  horse:'🐴 Cavalo', toucan:'🦜 Tucano', unicorn:'🦄 Unicórnio',
  emptyAll:'todo mundo', emptyHorse:'todos os cavalos', emptyToucan:'todos os tucanos',
  emptyTitle:'Isso é ', emptyBody1:'Você guardou ', emptyBody2:' deles. Nada se perde de verdade — o Guia de Campo continua com todos os ',
  againBtn:'Rever os que eu passei', galBtn:'Abrir o Guia de Campo',
  backThey:'De volta — sem ressentimentos',
  joined:' entrou no seu zoo', removed:' saiu do zoo', isBack:' está de volta',
  blankLib1:'Nada guardado ainda', blankLib2:' neste filtro', blankLib3:'.',
  blankLib4:'Deslize para a direita em alguém — ou guarde direto do Guia de Campo.',
  keep:'Guardar ', remove:'Remover do zoo',
  credit1:'Foto: Wikimedia Commons. ', credit2:' Nome e biografia inventados.',
  creditUni:'Foto: Wikimedia Commons (Lipizzano). O chifre foi acrescentado. Obviamente.',
  statHeight:'Altura', statBill:'Bico', statHorn:'Chifre',
  mare:'Égua', stallion:'Garanhão', female:'Fêmea', male:'Macho',
  undo:'Desfazer', pass:'Passar', like:'Apaixonar', readMore:'Ler mais'
},
p:{
h00:{species:'Akhal-Teke', origin:'Turcomenistão',
 bio:"Aristocrata do deserto passando um inverno na floresta, o que dizem que forja o caráter. Meu pelo tem um brilho metálico que sai mal nas fotos e estraga o retrato de grupo dos outros.",
 tags:['Pelo metálico','Melancolia de inverno','Linhagem do deserto'],
 prompt:['Meus prazeres simples','Ficar parado no tempo ruim até acharem que sou uma estátua.']},
h01:{species:'Appaloosa', origin:'Idaho, EUA',
 bio:"Nasci com um olho azul e a cara cheia de sardas, então nunca precisei desenvolver personalidade. Cada pinta está num lugar diferente do ano passado e ninguém sabe explicar.",
 tags:['Um olho azul','Sardento','Geneticamente confuso'],
 prompt:['Duas verdades e uma mentira','Minhas pintas se movem. Meu olho é azul. Sou um cavalo normal.']},
h02:{species:'Árabe', origin:'Península Arábica',
 bio:"Tenho uma vértebra a menos que a maioria de vocês e menciono isso o tempo todo. Perfil côncavo, cauda alta, cinco mil anos de papelada.",
 tags:['Linhagem antiga','Perfil côncavo','Refinada demais'],
 prompt:['Procuro alguém que','Aguente 160 km sem fazer drama.']},
h03:{species:'Camargue', origin:'Camargue, França',
 bio:"Nasci marrom como todo mundo, fiquei cinza, continuei cinza e vou ser branco para sempre. Moro num pântano salgado e meus cascos vivem úmidos — isso não é um problema, é um estilo de vida.",
 tags:['Vive no pântano','Fica branco','Cascos molhados'],
 prompt:['Um objetivo de vida','Ser fotografado galopando na água rasa. De novo. Profissionalmente.']},
h04:{species:'Clydesdale', origin:'Lanarkshire, Escócia',
 bio:"Uma tonelada de cavalo de tiro escocês em arreio completo. Uso antolhos porque me distraio com absolutamente qualquer coisa e todos concordamos que é melhor assim.",
 tags:['Pernas com franjas','Usa antolhos','Unidade absoluta'],
 prompt:['Não suporto','Qualquer coisa se mexendo na periferia. Não consigo ver. Está me destruindo.']},
h05:{species:'Pônei Exmoor', origin:'Exmoor, Inglaterra',
 bio:"Semisselvagem, totalmente indiferente. Tenho pelagem dupla de inverno, pálpebras à prova de neve e ligação genética comprovada com pôneis da Era do Gelo, então sim, vou ficar aqui fora.",
 tags:['Semisselvagem','Genética da Era do Gelo','À prova de tempo'],
 prompt:['Meu medo mais irracional','Manta. Alguém já tentou colocar uma manta em mim.']},
h06:{species:'Falabella', origin:'Buenos Aires, Argentina',
 bio:"Setenta e seis centímetros de pura confiança argentina. Eu sou um cavalo. Não um pônei. Não um cachorro. Um cavalo. Parem de perguntar, por favor.",
 tags:['Miniatura','Personalidade enorme','Corretamente um cavalo'],
 prompt:['A pior ideia que já tive','Tentar impor autoridade sobre um ganso.']},
h07:{species:'Fiorde Norueguês', origin:'Noruega Ocidental',
 bio:"Minha crina é aparada em pé para mostrar a listra preta do meio, o que dá trabalho e eu gostaria de algum reconhecimento por isso. Vikings me usavam. Raramente comento.",
 tags:['Corte vertical','Listra dorsal','Currículo viking'],
 prompt:['Tenho orgulho de','Uma crista tão firme que dá para apoiar um café.']},
h08:{species:'Frísio', origin:'Frísia, Países Baixos',
 bio:"Todo preto, todo drama. Faço charrete, adestramento e, como você vê, uma procissão histórica ocasional com um homem de capa vermelha. Nunca tive um dia sutil na vida.",
 tags:['Teatral','Preto absoluto','Franjas nas patas'],
 prompt:['Minha linguagem do amor','Chegar em algum lugar devagar, com música.']},
h09:{species:'Gypsy Cob', origin:'Grã-Bretanha e Irlanda',
 bio:"Pelagem malhada, franjas até o chão, topete cobrindo o focinho. Sinceramente, não enxergo nada e já fiz as pazes com isso. Me escovar é um compromisso de duas horas — fica o aviso.",
 tags:['Topete gigante','Malhado','Alta manutenção'],
 prompt:['Meu domingo típico','Sendo escovado. O dia inteiro. Escovação.']},
h10:{species:'Haflinger', origin:'Tirol do Sul',
 bio:"Corpo castanho, crina platinada, sempre despenteada pelo vento. Todo Haflinger vivo descende de um único garanhão nascido em 1874, então tecnicamente isto aqui é um encontro de família pequeno.",
 tags:['Crina clara','Alpino','Agressivamente fotogênica'],
 prompt:['Não saia comigo se','Você se intimida com cabelo bom.']},
h11:{species:'Cavalo Islandês', origin:'Islândia',
 bio:"Tenho cinco andamentos em vez de três. Um deles é o tölt, tão macio que dá para carregar um copo cheio. Se eu sair da Islândia, nunca mais posso voltar — então ando escolhendo bem as férias.",
 tags:['Cinco andamentos','Sem volta para casa','Extremamente peluda'],
 prompt:['O que surpreende as pessoas','Nenhum cavalo novo entra na Islândia desde o ano 982.']},
h12:{species:'Knabstrupper', origin:'Dinamarca',
 bio:"Dinamarquês, pintado, descendente de uma única égua chamada Flaebe que apareceu em 1812 coberta de pintas e fundou uma raça inteira. Contenho multidões. Umas duzentas, contáveis.",
 tags:['Pintas de leopardo','Herança circense','Dinamarquês'],
 prompt:['Um pensamento que tive no banho','Se eu ficar na sombra salpicada, fico invisível? (Não.)']},
h13:{species:'Konik', origin:'Polônia',
 bio:"Cinza-rato, com listra dorsal, usado em projetos de rewilding pela Europa — ou seja, meu emprego é ficar parado num pântano parecendo primitivo. Não paga nada e eu amo.",
 tags:['Listra dorsal','Profissional do rewilding','Tipo primitivo'],
 prompt:['A chave do meu coração','Não me cercar. Sério. Está no contrato.']},
h14:{species:'Lipizzano', origin:'Lipica, Eslovênia',
 bio:"Nasci preto, fiquei branco aos sete, como manda a tradição. Faço cabriola, um salto com coice no ar sem nenhuma finalidade prática, e vou fazer isso na sua festa.",
 tags:['Ares acima do solo','Nasceu escuro','Barroco'],
 prompt:['Meu assunto favorito','A forma da levade. A sua está ok. A minha está correta.']},
h15:{species:'Lusitano', origin:'Alentejo, Portugal',
 bio:"Cinza rodado, criado para a tourada, empregado no adestramento, poeta por dentro. Sou extremamente corajoso e extremamente dramático, e essas duas coisas são a mesma coisa.",
 tags:['Rodado','Ibérico','Corajoso e sombrio'],
 prompt:['Melhor história de viagem','Portugal. Inteiro. Nunca saí de lá.']},
h16:{species:'Mangalarga Marchador', origin:'Minas Gerais, Brasil',
 bio:"Brasileiro, alazão e marchador — minha marcha é de quatro tempos com contato constante no chão, ou seja, você nunca balança. Pergunte a qualquer um. Ninguém nunca balançou.",
 tags:['Marchador','Andar macio','Brasileiro'],
 prompt:['Algo que nunca mais farei','Trotar. Por quê? Eu tenho marcha.']},
h17:{species:'Marwari', origin:'Rajastão, Índia',
 bio:"Minhas orelhas curvam para dentro até as pontas se tocarem — é a marca do Marwari e também significa que ouço seu sarcasmo a uma distância considerável. Cavalo de guerra por criação, artista por escolha.",
 tags:['Pontas das orelhas curvas','Linhagem de cavalaria','Cerimonial'],
 prompt:['Um fato que sou obrigado a contar','Giro as orelhas 180 graus. Independentemente. Agora mesmo.']},
h18:{species:'Cavalo Mongol', origin:'Mongólia',
 bio:"Sim, sou aquele pontinho ao longe — a estepe faz isso com todo mundo. Somos mais numerosos que os humanos da Mongólia e vivemos quase sempre ao relento, cuidando da nossa vida.",
 tags:['Livre','Criado na estepe','Mais que os humanos'],
 prompt:['Meu primeiro encontro ideal','Quarenta quilômetros. Sem conversa. Perfeito.']},
h19:{species:'Mustangue', origin:'Nevada, EUA',
 bio:"Vivo solta, descendente de cavalos espanhóis que escaparam há quatrocentos anos e simplesmente nunca voltaram. Eu venho em bando. A gente anda junto. Espero que tudo bem.",
 tags:['Vive solta','Descendência espanhola','Vem em bando'],
 prompt:['Não calo a boca sobre','Fontes de água. Sei todas. Me pergunta. Por favor, me pergunta.']},
h20:{species:'Paint Horse', origin:'Texas, EUA',
 bio:"Porte de cavalo de trabalho, manchas tobiano e um olho de vidro que assusta estranhos nas exposições. Giro numa moeda e paro do galope em três passadas, o que é exibicionismo e eu sei.",
 tags:['Tobiano','Olho de vidro','Serve na fazenda'],
 prompt:['Me convença do contrário','Uma parada deslizante é uma personalidade.']},
h21:{species:'Cavalo de Przewalski', origin:'Estepe Mongol',
 bio:"O último cavalo realmente selvagem — nunca domesticado, extinto na natureza em 1969, de volta à estepe graças a muita gente teimosa em meu favor. Tenho 66 cromossomos. Você tem 64. Constrangedor.",
 tags:['Genuinamente selvagem','De volta da extinção','66 cromossomos'],
 prompt:['Quero alguém que','Entenda que não sou um pônei, sou um projeto à parte.']},
h22:{species:'Pônei Shetland', origin:'Ilhas Shetland',
 bio:"Quilo por quilo, o cavalo mais forte que existe, e escolhi usar esse poder para o crime. Este é meu lado bom. Estou rindo de algo que fiz mais cedo e que você ainda não descobriu.",
 tags:['Ameaça','Forte demais','Sem remorso'],
 prompt:['Como me conquistar','Você não vai. Você vai simplesmente aprender a conviver comigo.']},
h23:{species:'Shire', origin:'Inglaterra',
 bio:"O cavalo mais alto já registrado era dos meus — Sampson, 2,19 m, 1846, invicto até hoje. Puxo uma tonelada sem ofegar e minha crina precisa de pente próprio. Gentil. Enorme. Difícil de irritar.",
 tags:['Raça mais alta','Gigante gentil','Crina magnífica'],
 prompt:['Juntos poderíamos','Mover literalmente qualquer coisa. Diga o nome. Está movido.']},
h24:{species:'Suffolk Punch', origin:'Suffolk, Inglaterra',
 bio:"Todo Suffolk vivo descende de um garanhão nascido em 1768, e somos menos numerosos que os pandas-gigantes. Sempre alazã. Sempre. Não existe outra opção e a gente gosta assim.",
 tags:['Sempre alazã','Criticamente rara','Pernas limpas'],
 prompt:['Uma causa que me importa','Eu. Estatisticamente. Por favor.']},
t00:{species:'Tucano-andino-de-peito-cinza', origin:'Andes Peruanos',
 bio:"Moro na floresta de neblina a 3.000 metros, onde tudo é permanentemente úmido e coberto de musgo. Sou cinza, azul, castanho e vermelho ao mesmo tempo e ainda assim passo por discreto aqui em cima.",
 tags:['Floresta de neblina','Grande altitude','Fã de musgo'],
 prompt:['Meu lugar feliz','Dentro de uma nuvem. Tecnicamente sempre. Na prática, irritante.']},
t01:{species:'Tucano-de-bico-de-placa', origin:'Andes, Equador',
 bio:"Tenho uma placa amarela em relevo na lateral do bico — uma placa mesmo, tipo louça — e ninguém explicou direito por quê. Tenho pele turquesa em volta do olho. Sou, francamente, demais.",
 tags:['Placa no bico','Anel ocular turquesa','Anatomia inexplicada'],
 prompt:['A pergunta que faço sempre','Mas para que serve a placa?']},
t02:{species:'Tucano-andino-de-bico-preto', origin:'Colômbia',
 bio:"Colombiano, andino e das poucas por aqui que mantiveram o bom gosto no bico. Peito azul-acinzentado, dorso castanho e um toque de vermelho atrás que considero minha assinatura.",
 tags:['Discreta','Andina','Detalhe vermelho'],
 prompt:['Opinião impopular','Nem todo bico precisa ser laranja. Pronto. Falei.']},
t03:{species:'Tucaneta-esmeralda', origin:'México',
 bio:"Pequena, verde e completamente invisível dentro de uma folha — essa é a estratégia inteira. Faço ninho em buracos velhos de pica-pau porque construir é trabalho de outra pessoa e sempre foi.",
 tags:['Verde-folha','Ninho emprestado','Miúda'],
 prompt:['Sou estranhamente bom em','Ficar a um metro de você, sem ser visto, por uma hora.']},
t04:{species:'Tucaneta-de-bico-sulcado', origin:'Venezuela',
 bio:"Meu bico tem sulcos ao longo dele. Sulcos de verdade. Já me chamaram de analógico mais de uma vez e resolvi abraçar. Floresta de neblina venezuelana, permanentemente meio molhado.",
 tags:['Bico sulcado','Floresta de neblina','Analógico'],
 prompt:['Duas verdades e uma mentira','Tenho sulcos. Sou verde. Toco a 33 rotações.']},
t05:{species:'Araçari-de-pescoço-preto', origin:'Brasil',
 bio:"No momento inspecionando um oco de árvore, como faço quase toda tarde. Até seis de nós dormem no mesmo buraco, com a cauda dobrada sobre as costas feito gaveta de talheres. É indigno e muito quentinho.",
 tags:['Dorme em grupo','Nidifica em ocos','Cauda dobrável'],
 prompt:['Minha opinião mais polêmica','Seis não é demais para um oco. Sete é demais.']},
t06:{species:'Araçari-banana', origin:'Misiones, Argentina',
 bio:"Sou inteiramente amarela. Não com detalhes amarelos — amarela. Anel ocular vermelho, vermelho na base do bico, e todo o resto é açafrão puro. Mata Atlântica, ameaçada, inesquecível.",
 tags:['Inteiramente amarela','Anel ocular vermelho','Rara'],
 prompt:['Não me julgue se eu','Destoar de absolutamente tudo que você tem em casa.']},
t07:{species:'Araçari-de-crista-encaracolada', origin:'Peru',
 bio:"As penas da minha cabeça não são penas — são cachos pretos e brilhantes de queratina endurecida, tipo vinil. Eu nasci de permanente. A natureza me deu permanente e se recusa a explicar.",
 tags:['Cachos de vinil','Amazônico','Permanente natural'],
 prompt:['Minha maior qualidade','Cabelo que o tempo não estraga, porque não é cabelo.']},
t08:{species:'Araçari-castanho', origin:'Bolívia',
 bio:"Bochechas castanhas, peito amarelo, uma faixa vermelha na barriga feito cinto mal colocado. Ando em bandos barulhentos de uma dúzia, a gente chega toda junta e vai embora na hora.",
 tags:['Anda em bando','Faixa vermelha','Chegada barulhenta'],
 prompt:['Uma noite perfeita','Doze de nós. Uma figueira. Caos total. Em casa ao anoitecer.']},
t09:{species:'Araçari-miudinho', origin:'Amazônia',
 bio:"As marcas pretas no meu bico parecem caligrafia — daí o nome — e gente de verdade já passou tempo tentando ler. Não tem nada escrito ali. Eu conferi.",
 tags:['Bico caligráfico','Menor araçari','Ilegível'],
 prompt:['Me pergunte sobre','O que meu bico diz. A resposta é nada. Pergunte mesmo assim.']},
t10:{species:'Araçari-de-muitas-faixas', origin:'Equador',
 bio:"Duas faixas vermelhas sobre barriga amarela, capuz preto, pele azul em volta do olho. Eu saqueio ninho dos outros, um defeito de caráter no qual escolhi não trabalhar.",
 tags:['Duas faixas','Saqueia ninhos','Sem arrependimento'],
 prompt:['Eu provavelmente deveria me desculpar por','Você sabe o que eu fiz.']},
t11:{species:'Araçari-de-colar', origin:'Panamá',
 bio:"Empoleirada num galho com musgo, cuidando da minha vida, usando um colar castanho que não escolhi mas no qual me acostumei. Giro a cabeça 180 graus e durmo com o bico enfiado nas costas.",
 tags:['Colar castanho','Dorme dobrada','Galhos com musgo'],
 prompt:['Minha rotina de sono','Cabeça para trás, bico sob a asa, cauda por cima. Quinze segundos. Apagada.']},
t12:{species:'Araçari-verde', origin:'Suriname',
 bio:"O menor de todos os tucanos — uns 130 gramas, mais ou menos uma pera. Capuz preto se eu for macho, castanho se fêmea, e um bico listrado como uma fruta cítrica esquisita.",
 tags:['Menor tucano','Pesa uma pera','Bico cítrico'],
 prompt:['Pequeno, mas','Ainda vou pegar o melhor galho. Sempre. Observe.']},
t13:{species:'Tucanuçu', origin:'Pantanal, Brasil',
 bio:"O maior bico do ramo — um quinto do meu comprimento total — e não pesa quase nada, porque é uma colmeia de queratina e ar. Também uso como radiador. Sim, sério.",
 tags:['Maior tucano','Bico é radiador','Quase todo ar'],
 prompt:['Minha habilidade mais inútil','Meu bico dissipa calor sob demanda. Não impressiona ninguém em festa.']},
t14:{species:'Tucano-de-garganta-amarela', origin:'Costa Rica',
 bio:"Grande, barulhenta e responsável por aquele grito que atravessa o vale inteiro ao amanhecer. Dizem que parece um sapo. Acho isso ofensivo e, no geral, correto.",
 tags:['Barulhenta','Canta ao amanhecer','Parece um sapo'],
 prompt:['Meu pior hábito','Seis da manhã. Todo dia. Desculpa. Não vou parar.']},
t15:{species:'Tucano-do-Chocó', origin:'Chocó, Equador',
 bio:"Moro numa das florestas mais chuvosas do planeta — em partes do Chocó caem treze metros de chuva por ano. Meu bico é amarelo e minha perspectiva é úmida, porém esperançosa.",
 tags:['Especialista em chuva','Muito molhada','Bico amarelo'],
 prompt:['Algo com que fiz as pazes','Estar úmido. Perpetuamente. Tudo bem.']},
t16:{species:'Tucano-de-bico-verde', origin:'Mata Atlântica, Brasil',
 bio:"Também chamada de tucano-de-bico-verde, o que não faz justiça ao babador vermelho-alaranjado enorme. Fui flagrada numa pilha de frutos de palmeira, que é onde passo a maior parte dos dias, dando espetáculo.",
 tags:['Babador vermelho','Obcecada por frutas','Mata Atlântica'],
 prompt:['Meu emoji mais usado seria','🫐 mas de açaí. Não existe esse emoji. É uma injustiça.']},
t17:{species:'Tucano-de-bico-de-quilha', origin:'Belize',
 bio:"Verde, laranja, vermelho e azul — tudo num bico só, ao mesmo tempo, sem nenhuma coordenação. Ave nacional de Belize. Prefiro pular a voar sempre que possível, porque voar dá trabalho e eu não.",
 tags:['Bico arco-íris','Ave nacional','Prefere pular'],
 prompt:['Eu me apaixonaria se','Você me deixasse jogar uma fruta na sua cara. É corte. Confie em mim.']},
t18:{species:'Tucano-de-bico-de-quilha', origin:'Belize',
 bio:"Mesmo tronco, outro passarinho. Dormimos em quatro num oco, com o bico virado para trás e a cauda dobrada, o que parece horrível e funciona perfeitamente. Pergunte à minha colega Iris.",
 tags:['Bico arco-íris','Dividindo moradia','Vida baseada em tronco'],
 prompt:['Um interesse em comum seria','Este tronco. É um bom tronco. Quero falar sobre o tronco.']},
t19:{species:'Tucanuçu', origin:'Pantanal, Brasil',
 bio:"Vivo em área aberta — cerrado, buritizais, beira de rio — e não em mata fechada, o que faz de mim o tucano mais extrovertido que você vai encontrar. No momento numa figueira. Sempre no momento numa figueira.",
 tags:['Área aberta','Devoto de figo','Extrovertido'],
 prompt:['Me chame se','Você localizou fruta. É o critério inteiro.']},
t20:{species:'Tucano-de-papo-branco', origin:'Guiana',
 bio:"Babador branco impecável, corpo preto e um chamado que atravessa mais de um quilômetro de floresta fechada. Sou uma dispersora de sementes essencial, ou seja, árvores inteiras existem por causa da minha digestão.",
 tags:['Babador branco','Alcança 1 km','Planta florestas'],
 prompt:['Minha contribuição à sociedade','Algumas centenas de árvores. Passivamente. De nada.']},
t21:{species:'Tucano-de-bico-canelado', origin:'Amazônia',
 bio:"Garganta amarela virando um peito laranja profundo, pés azuis e sulcos — canais — ao longo de todo o bico. Sou a menor dos Ramphastos e tenho opiniões sobre ser chamada de compacta.",
 tags:['Cor de pôr do sol','Pés azuis','Bico canelado'],
 prompt:['Uma palavra que eu detesto','Compacta.']},
t22:{species:'Tucano-de-bico-canelado', origin:'Amazônia',
 bio:"Isto é um close do meu olho, porque ele é turquesa, cravado em pele azul nua, e eu gostaria que você olhasse com atenção. Sim, o resto de mim existe. Não é o ponto.",
 tags:['Olho turquesa','Pele azul nua','Sabe seu ângulo'],
 prompt:['Minha melhor característica','Discutida em detalhe acima. Continue olhando.']},
t23:{species:'Araçari-poca', origin:'Paraná, Brasil',
 bio:"Pequeno, verde-oliva, com pintas escuras num bico claro e uma mancha dourada na orelha. Morador da Mata Atlântica. Quieto. Frequentemente confundido com uma folha ambiciosa.",
 tags:['Bico pintado','Mancha dourada','Tipo quieto'],
 prompt:['Como se aproximar de mim','Devagar. Eu vou embora. Não é pessoal, é instinto.']},
t24:{species:'Araçari-de-colar-dourado', origin:'Peru',
 bio:"Cabeça preta, corpo castanho-oliva e um colar dourado fino no pescoço, feito colar muito discreto. Machos têm cabeça preta, fêmeas castanha — então dá para distinguir, o que ajuda.",
 tags:['Colar dourado','Dimorfismo sexual','Contido'],
 prompt:['Minha estética em três palavras','Um. Bom. Acessório.']},
h25:{species:'Akhal-Teke', origin:'Turcomenistão',
 bio:"Meu pelo tem uma estrutura que refrata a luz, que é o jeito científico de dizer que eu brilho. A raça está no brasão nacional do Turcomenistão. Guardo uma cópia.",
 tags:['Brilha de verdade','Está na moeda','Criado no deserto'],
 prompt:['Meu talento mais inútil','Estragar a foto dos outros por ser levemente luminoso.']},
h26:{species:'Quarto de Milha', origin:'Oklahoma, EUA',
 bio:"O cavalo mais rápido do mundo em quatrocentos metros — 88 km/h — e depois estou completamente acabada e preciso deitar. Somos a raça com mais registros do planeta, então modere as expectativas.",
 tags:['88 km/h','Velocista','Extremamente comum'],
 prompt:['Meu pior defeito','Fôlego. Me pergunte de novo daqui a quatrocentos metros.']},
h27:{species:'Appaloosa', origin:'Idaho, EUA',
 bio:"Pele mosqueada, cascos listrados e a esclera branca ao redor do olho, que me deixa com cara de permanentemente escandalizado. Não estou escandalizado. É só minha cara e eu agradeceria o benefício da dúvida.",
 tags:['Cascos listrados','Esclera visível','Não está escandalizado'],
 prompt:['Um mal-entendido comum sobre mim','Que acabei de ouvir alguma coisa chocante.']},
h28:{species:'Árabe', origin:'Península Arábica',
 bio:"No momento em arreio cerimonial com borlas roxas, o que não foi decisão minha mas que estou carregando muito bem. Tribos beduínas mantinham as éguas dentro da tenda da família. Nunca me recuperei desse padrão de hospedagem.",
 tags:['Cerimonial','Borlas roxas','Acostumada ao luxo'],
 prompt:['Onde me vejo em cinco anos','Dentro de casa. De preferência na sua tenda.']},
h29:{species:'Ardenês', origin:'Ardenas, Bélgica',
 bio:"Uma das raças de tração mais antigas da Europa — dizem que as legiões de César usaram meus ancestrais e que Napoleão nos levou à Rússia. Hoje em dia eu fico num campo. É um arranjo melhor para todo mundo.",
 tags:['Tração antiga','Currículo romano','Aposentado da guerra'],
 prompt:['Uma opinião que defendo até o fim','Puxar coisas é trabalho honesto. Adestramento é hobby.']},
h30:{species:'Camargue', origin:'Camargue, França',
 bio:"O escurinho é meu. Potros Camargue nascem pretos ou marrons e ficam brancos em quatro ou cinco anos, então por um tempo pareço ter adotado uma sombra pequena. Uma hora ele combina comigo.",
 tags:['Mãe','Nasceu escura','Égua do pântano'],
 prompt:['Algo que não esperava','O tanto que a minha personalidade viraria “mãe”.']},
h31:{species:'Falabella', origin:'Buenos Aires, Argentina',
 bio:"Reduzida ao longo de gerações numa única fazenda argentina até chegarmos aqui, mais ou menos do tamanho de um cachorro grande. Tenho o mesmo número de costelas de um cavalo inteiro, só que mais juntas. É um triunfo de projeto.",
 tags:['Criada em estância','Costelas completas','Tipo cachorro'],
 prompt:['Meu truque de festa','Passar por baixo das coisas. De todas as coisas.']},
h32:{species:'Pônei Fell', origin:'Cúmbria, Inglaterra',
 bio:"Preto, com franjas, construído pelo clima do lado errado dos Peninos. Eu carregava minério de chumbo pelas colinas para viver. Hoje troto por aí parecendo dramático na grama molhada, o que paga pior mas me cai bem.",
 tags:['Herança de carga','Franjas','Criado nas colinas'],
 prompt:['Meu domingo ideal','Chuva. Chuva horizontal. De preferência de lado.']},
h33:{species:'Fiorde Norueguês', origin:'Noruega Ocidental',
 bio:"Noventa por cento dos Fiordes são baios como eu, e todos temos a listra escura na crina e geralmente nas costas também. Somos uma das raças mais antigas e puras que existem. Também somos muito redondos.",
 tags:['Baia','Listra dorsal','Agradavelmente redonda'],
 prompt:['Um elogio que aceito','“Robusto.” Pode falar sem rodeios. Não me ofende.']},
h34:{species:'Gypsy Cob', origin:'Grã-Bretanha e Irlanda',
 bio:"Criado por famílias ciganas para puxar as carroças — por isso sou calmo, forte e estampado como uma vaca derrubada. No momento estou debruçado num portão. Fico debruçado nesse portão quase todo dia. O portão é meu agora.",
 tags:['Criado para carroça','Imperturbável','Dono de um portão'],
 prompt:['Você me encontra','No portão. Sempre no portão. Venha ao portão.']},
h35:{species:'Haflinger', origin:'Tirol do Sul',
 bio:"Criada nas montanhas dos Alpes, o que significa que piso firme em terreno que assusta todo mundo. O cabresto rosa foi um presente. Tenho sentimentos complicados sobre o cabresto rosa.",
 tags:['Pisa firme','Alpina','Em conflito com o rosa'],
 prompt:['Sem querer ser dramático mas','Eu poderia te carregar montanha abaixo. Estou escolhendo não fazer isso.']},
h36:{species:'Cavalo Islandês', origin:'Islândia',
 bio:"Aquilo atrás de mim é uma montanha islandesa de verdade, não um cenário. Somos chamados de cavalos, nunca de pôneis, e os islandeses são firmes nisso de um jeito que já acabou com amizades.",
 tags:['Cavalo, não pônei','Cenário vulcânico','Firme na terminologia'],
 prompt:['Não me chame de','Pônei. Estou pedindo com educação, uma vez.']},
h37:{species:'Knabstrupper', origin:'Dinamarca',
 bio:"Isto é um close. O resto de mim também é assim. Cada pinta tem um tamanho, um formato e um lugar diferente de onde estava na minha última foto, o que é crescimento ou bruxaria.",
 tags:['Complexo leopardo','Abstrato','Possivelmente bruxaria'],
 prompt:['Um elogio que recebo muito','“Isso é um cavalo de verdade?” Sim. Sim, é.']},
h38:{species:'Mangalarga Marchador', origin:'Minas Gerais, Brasil',
 bio:"Raça nacional do Brasil, tordilha rodada, e a maior raça registrada do mundo em livro de origem. Minha marcha é tão regular que cavaleiros já carregaram xícara cheia de café. Não recomendo testar com o meu café.",
 tags:['Raça nacional','Rodada','À prova de café'],
 prompt:['Pode me testar em','Qualquer coisa, menos no café.']},
h39:{species:'Nokota', origin:'Dakota do Norte, EUA',
 bio:"Rosilha azulada, descendente de cavalos que ficaram cercados por acidente dentro do Parque Nacional Theodore Roosevelt nos anos 1950 e simplesmente seguiram a vida. Alguns de nós vêm da tropa de Touro Sentado. Somos um erro burocrático histórico e estamos indo bem.",
 tags:['Rosilha azulada','Sobrevivente acidental','Criada na pradaria'],
 prompt:['Minha história de origem','Alguém construiu uma cerca no lugar errado. Eis-me aqui.']},
h40:{species:'Trotador Orlov', origin:'Rússia',
 bio:"Fundado pelo Conde Orlov em 1776 a partir de um garanhão árabe que ele obteve em circunstâncias que ninguém nunca explicou direito. Eu troto. É a modalidade inteira. Troto lindamente e rápido, e não galopo, obrigado.",
 tags:['Só trota','Linhagem imperial','Origem suspeita'],
 prompt:['Um limite que mantenho','Não vou galopar. Nem peça. Já conversamos sobre isso.']},
h41:{species:'Paint Horse', origin:'Texas, EUA',
 bio:"Manchas tobiano, porte de trabalho e um registro que não te aceita se seus pais não estavam na lista. Não fui eu que fiz as regras. Me beneficiei enormemente das regras.",
 tags:['Tobiano','Tipo trabalho','Beneficiada por nepotismo'],
 prompt:['Secretamente, eu','Estou de boa em ser famosa pelas manchas. Sinceramente, de boa.']},
h42:{species:'Paso Fino', origin:'Porto Rico',
 bio:"Meu andamento é um passo rápido e regular de quatro tempos que soa como aplauso em estrada dura. Tem três velocidades e todas são mais macias que qualquer coisa em que você já sentou. O nome quer dizer “passo fino”. Basicamente me batizei sozinho.",
 tags:['Quatro tempos','Soa como aplauso','Autobatizado'],
 prompt:['Me coloque em','Paralelepípedo. Aí feche os olhos e só escute.']},
h43:{species:'Percheron', origin:'Perche, França',
 bio:"Cinza, enorme e em arreio com a minha colega, que também se chama Huguette, o que causa problemas. Percherons são cavalos de tração com sangue árabe, então sou ao mesmo tempo um caminhão e, em certas luzes, elegante.",
 tags:['Tração','Sangue árabe','Conflito de nomes'],
 prompt:['Um problema recorrente na minha vida','Alguém chama. Nós duas vamos. Toda vez.']},
h44:{species:'Cavalo de Przewalski', origin:'Estepe Mongol',
 bio:"Sou um potro e já sou um caso de sucesso em conservação, o que é muita pressão para alguém que ainda não acha a própria mãe com confiabilidade. Todos nós vivos descendemos de cerca de doze indivíduos.",
 tags:['Potro','Ameaçado','Sob pressão'],
 prompt:['O que preciso de um parceiro','Paciência. Eu tenho um ano. Vou pisar em você.']},
h45:{species:'Pônei Shetland', origin:'Ilhas Shetland',
 bio:"Ruivo, peludo e de uma ilha onde o clima é uma ofensa pessoal. Shetlands trabalharam em minas de carvão por um século, então tenho histórico familiar de ficar debaixo da terra e ressentido com isso.",
 tags:['Ruivo','Linhagem de mina','Guarda rancor'],
 prompt:['Me pergunte sobre','As minas. Sente-se primeiro. Demora.']},
h46:{species:'Shire', origin:'Inglaterra',
 bio:"Aquela do meu lado é minha parceira de arreio. Trabalhamos juntas há seis anos e hoje nos movemos como um animal só com oito patas e duas opiniões, que costumam ser a mesma opinião.",
 tags:['Trabalha em dupla','Estrela branca','Sincronizada'],
 prompt:['Minha relação mais próxima','Ela. Desculpa. Você perguntou.']},
h47:{species:'Sorraia', origin:'Vale do Sorraia, Portugal',
 bio:"Existem menos de duzentos de nós no mundo. Pelagem baia, listra dorsal, listras de zebra nas pernas e uma cara igual à dos cavalos pintados nas cavernas da Ibéria. Andamos num grupo pequeno e sério.",
 tags:['Menos de 200 vivos','Listras nas pernas','Cara pré-histórica'],
 prompt:['Meu tipo','Alguém que entenda que a minha família inteira também está aqui.']},
h48:{species:'Tennessee Walker', origin:'Tennessee, EUA',
 bio:"Palomino, crina clara e um running walk que come dezesseis quilômetros por hora enquanto balanço a cabeça como se concordasse com tudo que você diz. Normalmente não concordo. O balanço é involuntário.",
 tags:['Running walk','Crina clara','Balanço involuntário'],
 prompt:['Me interprete corretamente','O balanço da cabeça é um andamento. Não é concordância.']},
h49:{species:'Pônei Galês', origin:'País de Gales',
 bio:"Pôneis galeses correm soltos naquelas colinas desde os tempos romanos, e Henrique VIII certa vez mandou destruir todos os cavalos pequenos para “melhorar o plantel”. Nós nos escondemos nas montanhas. Acabou mal para ele e bem para nós.",
 tags:['Sobreviveu a um Tudor','Criada nas colinas','Historicamente teimosa'],
 prompt:['Um rancor que mantenho','Henrique VIII. Sim, ainda. Ele começou.']},
h50:{species:'Marwari', origin:'Rajastão, Índia',
 bio:"Aqui estão elas. As pontas se tocam, ou quase, e giram 180 graus completos de forma independente uma da outra. Nenhum outro cavalo do planeta tem isso. Sei que você veio pelas orelhas. Todo mundo vem pelas orelhas.",
 tags:['As orelhas','Giro de 180°','Único no mundo'],
 prompt:['Olha, eu sei por que você está aqui','As orelhas. Pode olhar com calma. Eu espero.']},
t25:{species:'Tucano-andino-de-peito-cinza', origin:'Andes Peruanos',
 bio:"Flagrada no meio de uma fruta, que é mais ou menos oitenta por cento da minha vida acordada. Moro acima de 2.400 metros, onde as árvores são baixas, o musgo é grosso e ninguém nunca sentiu calor.",
 tags:['Focada em frutas','Altos Andes','Com frio sempre'],
 prompt:['Minha linguagem do amor','Te passar uma fruta. É o gesto inteiro. Não complique.']},
t26:{species:'Tucano-de-bico-de-placa', origin:'Andes, Equador',
 bio:"A placa amarela do meu bico é uma peça separada de queratina em relevo que aparentemente não serve para nada. Fiz as pazes com ser decorativa. Demorou.",
 tags:['Placa decorativa','Floresta de neblina','Em paz com isso'],
 prompt:['Algo que aceitei','Nem tudo precisa de motivo. Olhe para mim.']},
t27:{species:'Tucano-de-bico-de-placa', origin:'Andes, Equador',
 bio:"Restam cerca de 10 mil de nós e nossa floresta está indo embora em fatias. Ainda assim: pele turquesa no olho, uma mancha vermelha que ninguém espera e uma placa na cara. Pretendo ser memorável no caminho.",
 tags:['Quase ameaçado','Pele turquesa','Memorável'],
 prompt:['Minha filosofia','Ser extremamente conspícuo. Não funcionou ainda. Sigo firme.']},
t28:{species:'Tucano-andino-de-bico-preto', origin:'Colômbia',
 bio:"Colombiana, andina e turquesa nas costas de um jeito que sai mal na foto e fica extraordinário ao vivo. Você vai simplesmente ter que vir até os Andes. Eu não viajo.",
 tags:['Dorso turquesa','Andina','Não viaja'],
 prompt:['Se quiser me conhecer','Bogotá, e depois para cima. Traga casaco. Não vou me mover.']},
t29:{species:'Tucaneta-esmeralda', origin:'México',
 bio:"Corpo verde, bico amarelo e preto, garganta azul, vermelho embaixo da cauda. Pareço quatro pássaros diferentes combinados por um comitê que nunca se reuniu. Funciona. Ninguém sabe por quê.",
 tags:['Projeto de comitê','Garganta azul','Funciona de algum jeito'],
 prompt:['Um elogio que me acerta','“Isso não deveria combinar.” Correto. E ainda assim.']},
t30:{species:'Tucaneta-de-bico-sulcado', origin:'Venezuela',
 bio:"Floresta de neblina do litoral venezuelano, que é uma faixa estreita de montanha muito molhada com aves que não existem em nenhum outro lugar. Sou uma delas. Meu bico tem sulcos. Já falamos disso.",
 tags:['Quase endêmico','Bico sulcado','Cordilheira costeira'],
 prompt:['Me pergunte literalmente outra coisa','Eu ainda vou trazer os sulcos de volta.']},
t31:{species:'Araçari-de-pescoço-preto', origin:'Brasil',
 bio:"Bico amarelo-claro, capuz preto, uropígio vermelho e uma pele azul nua em volta do olho que muda de tom conforme o meu humor. Isto não é metáfora. É literalmente um anel do humor na minha cara.",
 tags:['Cara que muda de cor','Traseiro vermelho','Pele azul'],
 prompt:['Como me ler','Olhe a minha cara. A cor é a resposta. Nunca é boa notícia.']},
t32:{species:'Araçari-de-crista-encaracolada', origin:'Peru',
 bio:"Estes cachos são placas achatadas, endurecidas e brilhantes — mais próximas de plástico que de penas. Ninguém sabe para que servem. Já me perguntaram do meu cabelo todos os dias da minha vida adulta.",
 tags:['Cachos de plástico','Inexplicado','Perguntam diariamente'],
 prompt:['A pergunta que me cansou','“Isso é de verdade?” Está preso na minha cabeça. Tire suas conclusões.']},
t33:{species:'Araçari-de-crista-encaracolada', origin:'Peru',
 bio:"Amazônia ocidental, ao sul do rio, no dossel onde ficam as figueiras. Ando num grupo de oito e dormimos todos num oco só. Os cachos não ajudam nisso. Os cachos nunca ajudaram em nada.",
 tags:['Vive no dossel','Grupo de oito','Cabelo impraticável'],
 prompt:['Minha avaliação honesta','Cabelo lindo, estruturalmente inútil. Como quase tudo que é lindo.']},
t34:{species:'Araçari-castanho', origin:'Bolívia',
 bio:"Fotografado ao lado de um mamão, o que não é coincidência. Localizei todas as árvores frutificando num raio de quatro quilômetros quadrados e mantenho a lista de cabeça. Me pergunte qualquer coisa sobre fruta.",
 tags:['Cartógrafo de frutas','Chegado num mamão','Enciclopédico'],
 prompt:['Minha especialidade','Qual árvore está madura. E quando. Nunca erro isso.']},
t35:{species:'Araçari-castanho', origin:'Bolívia',
 bio:"Contra um céu limpo, pela primeira vez, o que quase nunca acontece porque eu vivo no sub-bosque. A faixa vermelha na barriga, a mancha castanha da orelha, o amarelo — tudo fica bem mais alto na luz do dia e não me arrependo de nada.",
 tags:['Faixa na barriga','Vive no sub-bosque','Alto na luz do dia'],
 prompt:['Um evento raro','Eu, visível, contra o céu. Aproveite. Não vai durar.']},
t36:{species:'Araçari-miudinho', origin:'Amazônia',
 bio:"O menor araçari da Amazônia, e os riscos pretos do meu bico realmente parecem uma assinatura. O bico dos machos tem mais riscos que o das fêmeas, então tecnicamente sou o sexo mais anotado.",
 tags:['Bico anotado','Menor araçari','Dimorfismo sexual'],
 prompt:['Um fato que uso em festas','Minha cara tem mais coisa escrita que a sua.']},
t37:{species:'Araçari-de-muitas-faixas', origin:'Equador',
 bio:"Duas faixas pretas sobre a barriga amarela, o que é uma faixa a mais do que a maioria dos meus parentes consegue, e eu faço questão de mencionar. Amazônia ocidental, dossel alto, geralmente gritando.",
 tags:['Duas faixas','Dossel alto','Geralmente gritando'],
 prompt:['Meu lado competitivo','Uma faixa a mais. É isso. É a rivalidade inteira.']},
t38:{species:'Araçari-de-colar', origin:'Panamá',
 bio:"Centro-americano, comunitário e extremamente envolvido na vida alheia. Até seis adultos ajudam a criar uma ninhada, o que parece comovente até você assistir às reuniões.",
 tags:['Criação cooperativa','Fofoqueiro','Decide em comitê'],
 prompt:['Algo que me esgota','Decisão em grupo. Seis opiniões. Um buraco de ninho.']},
t39:{species:'Araçari-verde', origin:'Suriname',
 bio:"No chão, brevemente, o que é incomum e levemente constrangedor para uma ave de dossel. Sou a menor de todos os tucanos que existem. Por favor, não comente a parte do chão.",
 tags:['Menor tucano','Raramente no chão','Constrangida'],
 prompt:['Não vamos discutir','A fotografia. Seguindo em frente.']},
t40:{species:'Tucano-de-bico-de-quilha', origin:'Costa Rica',
 bio:"Meu bico é verde na base, laranja na lateral, vermelho na ponta e azul embaixo, e não pesa quase nada porque é basicamente treliça oca e ar. Estruturalmente, sou uma esponja muito colorida.",
 tags:['Bico de quatro cores','Treliça oca','Esponja colorida'],
 prompt:['Eu sou basicamente','Espuma estrutural. Não conte para ninguém.']},
t41:{species:'Tucano-de-garganta-amarela', origin:'Costa Rica',
 bio:"A maior da América Central e alta o bastante para ser ouvida do vale vizinho. Engulo fruta inteira e regurgito a semente a alguma distância, o que faz de mim ao mesmo tempo um cliente e um serviço de entrega.",
 tags:['Maior da região','Entrega sementes','Voz que viaja'],
 prompt:['Meu bico extra','Reflorestamento. Não remunerado. Contínuo. Involuntário.']},
t42:{species:'Tucano-de-garganta-amarela', origin:'Costa Rica',
 bio:"Dividindo galho com uma bromélia, que guarda a própria piscina particular de água da chuva com sapos morando dentro. Meu bairro inteiro é assim. Tudo aqui contém outra coisa.",
 tags:['Vizinha bromélia','Floresta tropical','Ecossistemas aninhados'],
 prompt:['Algo que me espanta todo dia','Tem sapo dentro daquela planta. Sapo. Dentro da planta.']},
t43:{species:'Tucano-do-Chocó', origin:'Chocó, Equador',
 bio:"Estou restrita a uma faixa úmida e estreita entre os Andes e o Pacífico, que é um dos lugares mais biodiversos do planeta e também um dos que desaparecem mais rápido. Sem pressão para nenhum de nós dois.",
 tags:['Distribuição restrita','Hotspot de biodiversidade','Discretamente preocupada'],
 prompt:['Um pensamento recorrente','Antes tinha mais floresta. É o pensamento inteiro.']},
t44:{species:'Tucano-de-bico-verde', origin:'Mata Atlântica, Brasil',
 bio:"Garganta amarelo-alaranjada virando uma faixa vermelha no peito, que lê como um colete bastante confiante. Moradora da Mata Atlântica, ou seja, moro nos sete por cento que sobraram dela.",
 tags:['Colete confiante','Mata Atlântica','Sete por cento'],
 prompt:['Meu guarda-roupa','Um colete. Usado diariamente. Nunca removido. Comprometida.']},
t45:{species:'Tucano-de-bico-verde', origin:'Mata Atlântica, Brasil',
 bio:"Pendurada de cabeça para baixo numa palmeira porque a fruta está lá embaixo e dignidade é luxo. Tucanos como eu são o principal motivo de a juçara ainda se espalhar — a semente precisa passar por uma ave deste tamanho.",
 tags:['De cabeça para baixo','Especialista em palmeira','Ecologicamente essencial'],
 prompt:['Minha descrição de cargo','Comer a fruta. Voar. Produzir uma árvore. Repetir.']},
t46:{species:'Tucanuçu', origin:'Pantanal, Brasil',
 bio:"A palavra “tucano” vem do tupi, e meu nome também, mais ou menos. Sou aquele que todo mundo imagina: corpo preto, babador branco, bico laranja absurdo. Sou o tucano padrão e carrego isso com profissionalismo.",
 tags:['O tucano padrão','Nome tupi','Profissional'],
 prompt:['Meu fardo','Ser o da caixa de cereal. Todo mundo espera coisas.']},
t47:{species:'Tucano-de-papo-branco', origin:'Guiana',
 bio:"Dois de nós num galho só, o que é ou um par ou uma briga, e sinceramente é difícil saber de fora. Tucanos se cortejam jogando fruta um no outro, então a linha é tênue.",
 tags:['Em dupla, talvez','Corte com frutas','Ambíguo'],
 prompt:['Nosso status de relacionamento','Em negociação. Frutas foram atiradas. As interpretações divergem.']},
t48:{species:'Tucano-de-bico-canelado', origin:'Amazônia',
 bio:"Ao lado de uma folha mais ou menos do meu tamanho, o que põe a floresta inteira em perspectiva. Os sulcos do meu bico se chamam canais e percorrem ele todo. Tudo aqui é maior do que precisa ser.",
 tags:['Ofuscada por uma folha','Bico canelado','Noção de escala'],
 prompt:['Algo em que penso','Por que aquela folha é tão grande. Por que qualquer coisa é tão grande.']},
t49:{species:'Araçari-de-colar-dourado', origin:'Peru',
 bio:"Colar dourado fino, capuz preto, corpo oliva e uma mancha vermelha atrás que só aparece quando eu me viro. Fui projetado para ser revelado aos poucos. É exaustivo para todo mundo.",
 tags:['Colar dourado','Vermelho escondido','Revelação gradual'],
 prompt:['Como me apreciar','Devagar. De vários ângulos. Traga tempo.']},
u00:{species:'Unicórnio', origin:'Supostamente Avalon',
 bio:"Um unicórnio de verdade. Mil e duzentos anos, um desejo concedido por milênio, e já usei o deste milênio em algo sobre o qual prefiro não entrar em detalhes. Atualmente residindo num estábulo por questões fiscais.",
 tags:['Mítico','Concede desejos (raramente)','Arranjo fiscal'],
 prompt:['A pergunta que sempre recebo','Se o chifre é colado. Não é. Próxima pergunta.']}
}};
